import manifest from '../../public/divisions/manifest.json';
import mediaManifest from '../../public/media/manifest.json';

/**
 * Image metadata generated alongside the artwork by
 * `node scripts/generate-division-images.mjs`.
 *
 * Importing the manifest rather than hardcoding dimensions means `next/image`
 * always gets the true intrinsic size and a real LQIP blur, and both stay
 * correct when the artwork is regenerated or replaced.
 */
export interface DivisionImageMeta {
  /** Full-size artwork, served through next/image. */
  src: string;
  /**
   * A 512x320 copy for the WebGL slab. three.js fetches the raw file - it
   * cannot use next/image's optimised variants - so the scene gets its own
   * small texture instead of the full-size original.
   *
   * Absent on `hero-backdrop`, which is a DOM image only and never a texture.
   */
  texture?: string;
  /** Unsplash photo id, for looking the photographer up. See the fetch script. */
  unsplashId?: string;
  credit?: string;
  width: number;
  height: number;
  blurDataURL: string;
}

const images = manifest as Record<string, DivisionImageMeta>;

export function imageMeta(slug: string): DivisionImageMeta | undefined {
  return images[slug];
}

/**
 * The second manifest: photography for the pages that are not one of the seven
 * division cards - the security microsite, the automotive sourcing page and
 * careers. Generated by `node scripts/fetch-page-images.mjs`.
 *
 * Kept separate from the division manifest on purpose. The division set is
 * addressed by division slug and is consumed by the 3D scene; this one is
 * addressed by an arbitrary key and never becomes a texture.
 */
const media = mediaManifest as Record<string, DivisionImageMeta>;

export function mediaMeta(key: string): DivisionImageMeta | undefined {
  return media[key];
}

/**
 * Responsive `sizes` presets. Getting these right is the difference between
 * shipping a 1280px image to a 375px phone and shipping a 375px one.
 */
export const imageSizes = {
  /** Full-width single column on mobile, half the shell at md+, third at xl. */
  gridCard: '(min-width: 1280px) 30vw, (min-width: 768px) 46vw, 100vw',
  /** The division page hero: roughly half the shell on desktop. */
  pageHero: '(min-width: 1024px) 46vw, 100vw',
  /** Small square thumbnail inside the journey overlay card. */
  thumb: '96px',
  /** The reduced-motion / lite static strip. */
  strip: '(min-width: 768px) 33vw, 80vw',
  /** Full-bleed page hero (security, automotive, careers). */
  banner: '100vw',
  /** A product card in the 1 / 2 / 3-up security grid. */
  productCard: '(min-width: 1024px) 31vw, (min-width: 640px) 46vw, 100vw',
  /** One of a two-up split (home vs business, one-app). */
  split: '(min-width: 1024px) 48vw, 100vw',
  /** A small square inside a testimonial or process row. */
  tile: '(min-width: 768px) 30vw, 90vw',
} as const;
