import type { FieldConfig, FormConfig } from '@/lib/form-schema';
import type { DivisionTheme } from '@/config/theme';
import { site } from '@/config/site';
import { SOURCING_DISCLAIMER } from '@/config/automotive';

/* =========================================================================
   THE ONLY FILE YOU EDIT TO ADD A DIVISION.

   Navigation, the homepage grid, the 3D scroll beats, /services/[division]
   routing, the inquiry form, metadata and sitemap.xml all render from this
   array. See README.md > "Adding a division".
   ========================================================================= */

export interface DivisionService {
  title: string;
  body: string;
}

export interface Division {
  /** URL segment: /services/<slug> */
  slug: string;
  /** Full name, used in headings and metadata. */
  name: string;
  /** Compact name for nav and cards. */
  shortName: string;
  /** One line, sentence case, no period. */
  tagline: string;
  /** 1-2 sentences under the H1. */
  summary: string;
  /** Body copy, one string per paragraph. */
  body: string[];
  /** Rendered as the "What we do" list. */
  services: DivisionService[];
  /**
   * Heading over the services list. Defaults to "<name> services", which is
   * right for most divisions and wrong for the ones whose name already ends in
   * a noun that means "services".
   */
  servicesTitle?: string;
  /**
   * Who this division is for.
   *
   * Drives the "Home & personal / Business" split on the homepage. Eight
   * service pages side by side read as eight unrelated businesses; sorted by
   * who they serve, they read as one company covering both halves of a
   * customer's life. Several divisions genuinely serve both and appear twice,
   * which is the honest answer.
   */
  audience: ('home' | 'business')[];
  /** One line, for the audience lists. What this does FOR that customer. */
  audienceLine: string;
  /** Short trust / at-a-glance points. */
  highlights: string[];
  /**
   * The division's colour, used everywhere at once: the card, the page hero,
   * the form focus ring, the active rail tick and the 3D slab's edge glow.
   * Verified for WCAG AA by `node scripts/check-contrast.mjs`.
   */
  theme: DivisionTheme;
  /**
   * The division's artwork. Generated by
   * `node scripts/generate-division-images.mjs`; swap the file at `src` for
   * real photography without touching any component. See README > Imagery.
   */
  image: { src: string; alt: string };
  /** The geometry archetype for this division's 3D scroll moment. */
  scene: {
    shape: 'slab' | 'ring' | 'prism' | 'lattice' | 'column' | 'arc' | 'stack' | 'people';
  };
  /** Optional legal/regulatory notice rendered prominently on the page. */
  notice?: string;
  /** "How it works" steps. Optional; the section hides when absent. */
  process?: { title: string; body: string }[];
  /** Heading over the process section. Defaults to "Start to finish." */
  processTitle?: string;
  /** "Why us" points. Optional; the section hides when absent. */
  why?: { title: string; body: string }[];
  /** FAQs, rendered as an accordion with FAQPage JSON-LD. Optional. */
  faqs?: { question: string; answer: string }[];
  form: FormConfig;
  seo: { title: string; description: string };
}

const contactBlock = (extra = ''): string =>
  `Tell us what you need and we will come back with next steps.${extra ? ` ${extra}` : ''}`;

/** What a phone camera produces, plus what a desktop is likely to have saved. */
export const PHOTO_ACCEPT = '.jpg,.jpeg,.png,.webp,.heic,.heif';
export const PHOTO_MAX_FILES = 6;

/**
 * A "send us photos" field.
 *
 * Photos are what let the moving and cleaning teams quote a real number
 * instead of an hourly guess - a picture of the room answers "how much stuff
 * is there" in a way no description does. They are shrunk in the browser
 * before upload (src/lib/compress-image.ts), so six phone photos are a normal
 * upload rather than 40MB.
 */
export const PHOTO_FIELD = ({
  name = 'photos',
  label,
  help,
}: {
  name?: string;
  label: string;
  help: string;
}): FieldConfig => ({
  name,
  label,
  type: 'file',
  accept: PHOTO_ACCEPT,
  multiple: true,
  maxFiles: PHOTO_MAX_FILES,
  compressImages: true,
  help,
});

export const divisions: Division[] = [
  /* ---------------------------------------------------------------- 1 */
  {
    slug: 'security-smart-home',
    name: 'Security & Smart Home',
    shortName: 'Security',
    tagline: 'Alarms, cameras and connected homes',
    summary:
      'Alarm systems, cameras, video doorbells and smart-home equipment, supplied, installed and serviced.',
    body: [
      'A security setup only works if it is specified for the actual building and the people in it. We look at the property, recommend equipment that fits, install it properly and stay available when something needs adjusting.',
      'The same team handles smart-home equipment, so lighting, locks, thermostats and cameras end up on one coherent setup rather than five apps that do not talk to each other.',
    ],
    services: [
      {
        title: 'Smart systems',
        body: 'Protect your property with advanced automation and monitoring.',
      },
      {
        title: '24/7 monitoring',
        body: 'Reliable, real-time security for peace of mind.',
      },
      {
        title: 'Cameras & doorbells',
        body: 'Camera placement, video doorbells and recording setup for homes and businesses.',
      },
      {
        title: 'Smart-home equipment',
        body: 'Smart locks, lighting, thermostats and hubs configured to work together.',
      },
      {
        title: 'Installation',
        body: 'Professional setup for seamless, secure home integration.',
      },
    ],
    audience: ['home', 'business'],
    audienceLine: 'Alarms, cameras and smart-home kit, fitted and monitored.',
    highlights: [
      'Authorized Brinks Home Security dealer',
      '24/7 monitoring',
      'Professional installation',
    ],
    theme: {
      accent: '#5A3FC0',
      accentInk: '#4A3399',
      accentSoft: '#EDE9F9',
      accentContrast: '#FFFFFF',
      accentBright: '#B39CFA',
      glow: '#9182D4',
    },
    image: {
      src: '/divisions/security-smart-home.jpg',
      alt:
        'A smart-home sensor lit in blue and magenta.',
    },
    scene: { shape: 'lattice' },
    notice:
      'TKG Ventures Ltd is an authorized dealer of Brinks Home Security, delivering professional home security and smart automation solutions across select markets.',
    form: {
      title: 'Security & smart home inquiry',
      intro: contactBlock('Tell us about the property and what you want covered.'),
      submitLabel: 'Send security inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'house', label: 'House' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'retail', label: 'Retail unit' },
            { value: 'office', label: 'Office' },
            { value: 'warehouse', label: 'Warehouse / industrial' },
          ],
        },
        {
          name: 'systems',
          label: 'What are you interested in?',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'alarm', label: 'Alarm system' },
            { value: 'cameras', label: 'Security cameras' },
            { value: 'doorbell', label: 'Video doorbell' },
            { value: 'locks', label: 'Smart locks' },
            { value: 'lighting', label: 'Smart lighting' },
            { value: 'thermostat', label: 'Smart thermostat' },
          ],
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'new-install', label: 'New installation' },
            { value: 'upgrade', label: 'Upgrade existing system' },
            { value: 'service', label: 'Service or repair' },
            { value: 'equipment-only', label: 'Equipment purchase only' },
          ],
        },
        {
          name: 'address',
          label: 'Service address',
          type: 'address',
          required: true,
          span: 'half',
          placeholder: 'Start typing the address',
          help: 'Pick your address from the list as it appears.',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Number of entry points, existing equipment, coverage areas, monitoring preference.',
        },
      ],
    },
    seo: {
      title: 'Security & Smart Home: alarms, cameras and installation',
      description:
        'Alarm systems, security cameras, video doorbells and smart-home equipment. Supply, installation and service from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 2 */
  {
    slug: 'telecommunications',
    name: 'Telecommunications',
    shortName: 'Telecom',
    tagline: 'Internet, TV and phone, without the runaround',
    summary: 'Internet, television and phone plans, compared, explained and set up.',
    body: [
      'Telecom pricing is deliberately hard to compare. This division does the comparing for you: what is actually available at your address, what the real monthly cost looks like after promotional periods, and whether switching is worth the effort.',
      'We handle home and business connections, new installs and switches from an existing provider.',
    ],
    services: [
      {
        title: 'Internet',
        body: 'Home and business internet plans matched to how you actually use the connection.',
      },
      { title: 'Television', body: 'TV packages and streaming alternatives, compared honestly.' },
      { title: 'Phone', body: 'Home phone and mobile plans, including business lines.' },
      {
        title: 'Offers & switching',
        body: 'Current promotions and help moving from your existing provider.',
      },
    ],
    audience: ['home', 'business'],
    audienceLine: 'Internet, TV and phone plans that are actually available at your address.',
    highlights: ['Home & business', 'Plan comparison', 'Switching support'],
    theme: {
      accent: '#08718F',
      accentInk: '#065A72',
      accentSoft: '#DEF0F6',
      accentContrast: '#FFFFFF',
      accentBright: '#4FCBEB',
      glow: '#46A9C6',
    },
    image: {
      src: '/divisions/telecommunications.jpg',
      alt:
        'Illuminated fibre-optic strands against a black background.',
    },
    scene: { shape: 'arc' },
    processTitle: 'Signed up in four steps.',
    process: [
      {
        title: 'Tell us what you have',
        body: 'Your address, what you are paying now, and what actually annoys you about it: speed, price, the TV package, the contract.',
      },
      {
        title: 'We compare the real options',
        body: 'The plans available at your address, with the promotional price and the price it becomes afterwards side by side.',
      },
      {
        title: 'You pick, we set it up',
        body: 'We place the order and book the installation or arrange the self-install kit. We guide you through switching from your existing provider.',
      },
      {
        title: 'One number afterwards',
        body: 'Billing question, outage or upgrade: you call us and we deal with the provider, rather than you sitting in their queue.',
      },
    ],
    why: [
      {
        title: 'We are not tied to a single carrier',
        body: 'The recommendation is the plan that fits, not the one paying the biggest commission this month.',
      },
      {
        title: 'The price after the promo, in writing',
        body: 'Introductory pricing is where most telecom regret comes from. We show both numbers before you sign anything.',
      },
      {
        title: 'Business lines too',
        body: 'Multi-line phone, business internet with a static IP, and the paperwork that comes with moving an office.',
      },
      {
        title: 'Local, and answerable',
        body: 'The same person who signed you up is the person who picks up when something goes wrong.',
      },
    ],
    faqs: [
      {
        question: 'Do I pay extra for going through you?',
        answer:
          'No. You pay the provider the same plan price you would pay direct. We are compensated by the provider for the signup, which is why we say the recommendation is the plan that fits rather than the one that pays the most.',
      },
      {
        question: 'Can you get me out of my current contract?',
        answer:
          'Sometimes. It depends on the provider and how far in you are. We will tell you the real cancellation cost before you switch, and whether a new provider will cover part of it.',
      },
      {
        question: 'How long does a switch take?',
        answer:
          'Internet and TV are typically live within a few days of ordering, depending on installation availability in your building. Phone number transfers usually take a couple of business days.',
      },
      {
        question: 'Do you handle business accounts?',
        answer:
          'Yes. Business internet, multi-line phone systems and TV for waiting rooms and hospitality. Tell us how many lines and seats and we will come back with options.',
      },
    ],
    /*
     * The telecom form is an AVAILABILITY CHECK, not a general inquiry: the
     * address comes first and everything else follows from it, because the
     * address is what decides which plans exist at all. It is rendered as a
     * two-step flow by <AvailabilityCheck>; the field ORDER below is the order
     * the customer sees inside step two.
     */
    form: {
      title: 'Check available plans',
      intro:
        'A few details about the connection you want, and we will come back with what is actually available at your address and what it really costs.',
      submitLabel: 'Check Available Plans',
      successTitle: 'Thanks, we’re on it.',
      successBody:
        'We’re checking the best available options for your address. A representative will contact you with available plans and promotions shortly.',
      fields: [
        {
          name: 'address',
          label: 'Service address',
          type: 'address',
          required: true,
          placeholder: 'Enter your home or business address',
          help: 'Start typing and pick your address from the list.',
        },
        {
          name: 'accountType',
          label: 'Is this for a home or a business?',
          type: 'radio',
          required: true,
          options: [
            { value: 'home', label: 'Home' },
            { value: 'business', label: 'Business' },
          ],
        },
        {
          name: 'lookingFor',
          label: 'What are you looking for?',
          type: 'radio',
          required: true,
          options: [
            { value: 'internet', label: 'Internet' },
            { value: 'internet-tv', label: 'Internet + TV' },
            { value: 'internet-tv-phone', label: 'Internet + TV + Home Phone' },
            { value: 'business-internet', label: 'Business Internet' },
            { value: 'not-sure', label: 'Not sure / show me the best options' },
          ],
        },
        {
          name: 'currentProvider',
          label: 'Current provider',
          type: 'radio',
          required: true,
          options: [
            { value: 'telus', label: 'TELUS' },
            { value: 'rogers', label: 'Rogers' },
            { value: 'bell', label: 'Bell' },
            { value: 'other', label: 'Other' },
            { value: 'none', label: 'None / new service' },
          ],
        },
        {
          name: 'currentBill',
          label: 'Current monthly bill (optional)',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. $135',
          help: 'Roughly what you pay now. It is what we compare against.',
        },
        {
          name: 'billUpload',
          label: 'Upload your latest bill (optional)',
          type: 'file',
          span: 'half',
          accept: '.pdf,.jpg,.jpeg,.png,.webp,.heic,.heif',
          multiple: true,
          maxFiles: 3,
          compressImages: true,
          help: 'A photo or PDF of the bill. It lets us compare like for like, including the promotional pricing you are on now.',
        },
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'details',
          label: 'Anything else? (optional)',
          type: 'textarea',
          rows: 4,
          placeholder:
            'Speed, contract length, number of users, channels you actually watch, or a move-in date.',
        },
      ],
    },
    seo: {
      title: 'Telecommunications: internet, TV and phone plans',
      description:
        'Internet, television and phone plans for home and business, compared and set up by TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 3 */
  {
    slug: 'automotive',
    name: 'Automotive',
    shortName: 'Automotive',
    tagline: 'We find the car. You choose it.',
    summary:
      'A personal vehicle sourcing service: tell us what you are looking for, and we search our dealership network on your behalf.',
    body: [
'This division is a concierge, not a car lot. We hold no inventory and we are not a licensed dealership. What we do is take your requirements, search the dealerships we work with, and come back with vehicles that actually match, then introduce you to the dealer holding the one you want.',
      'The same works in reverse. If you are selling, we put the vehicle in front of buyers and dealership partners rather than leaving you to field messages from strangers.',
    ],
    services: [
      {
        title: 'Vehicle sourcing',
        body: 'Tell us the make, model, budget and timeline. We search our dealership network on your behalf and bring back a shortlist.',
      },
      {
        title: 'Dealer introductions',
        body: 'We introduce you to the licensed dealership selling the vehicle you choose, and stay involved through to handover.',
      },
      {
        title: 'Selling assistance',
        body: 'Help preparing and pricing a vehicle you want to move, and connecting you with a buyer or dealership partner.',
      },
      {
        title: 'Inspection coordination',
        body: 'Arranging pre-purchase inspection and servicing before you commit.',
      },
      {
        title: 'Solutions for dealerships',
        body: 'Lead generation and digital support for the dealership partners we source through.',
      },
    ],
    audience: ['home'],
    audienceLine: 'We find the vehicle you are after and introduce you to the dealer selling it.',
    highlights: [
      'Sourced to your exact specification',
      'Searched across a network of licensed dealerships',
      'No inventory, no lot, no pressure to take what is in stock',
    ],
    theme: {
      accent: '#BC4A17',
      accentInk: '#96380F',
      accentSoft: '#FBEBE2',
      accentContrast: '#FFFFFF',
      accentBright: '#FF9163',
      glow: '#FF8A4C',
    },
    image: {
      src: '/divisions/automotive.jpg',
      alt:
        'A line of dark vehicles parked under low showroom lighting.',
    },
    scene: { shape: 'slab' },
    notice: SOURCING_DISCLAIMER,
    form: {
      title: 'Automotive inquiry',
      intro: contactBlock('The more detail on the vehicle, the faster we can help.'),
      submitLabel: 'Send automotive inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'What do you need?',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'buying', label: 'I am looking to buy' },
            { value: 'selling', label: 'I am looking to sell' },
            { value: 'sourcing', label: 'Find a specific vehicle for me' },
            { value: 'service', label: 'Servicing or inspection' },
          ],
        },
        {
          name: 'vehicle',
          label: 'Make / model of interest',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. Toyota RAV4, 2019+',
        },
        {
          name: 'budget',
          label: 'Budget range',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 18,000 - 25,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '2-4-weeks', label: 'Within 2-4 weeks' },
            { value: '1-3-months', label: '1-3 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'Condition, mileage, trim, financing needs, or anything else that helps.',
        },
      ],
    },
    seo: {
      title: 'Automotive: personal vehicle sourcing',
      description:
        'Tell us what you are looking for and we search our dealership network on your behalf. Vehicle sourcing, dealer introductions and selling assistance from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 4 */
  {
    slug: 'real-estate',
    name: 'Real Estate',
    shortName: 'Real Estate',
    tagline: 'Connected to licensed representation',
    summary: 'Properties for sale, buy and sell assistance, and introductions to licensed realtors.',
    body: [
      'Property decisions are rarely just about the property. Our real estate division helps you get oriented: what is on the market, what your place might be worth, and what the process actually looks like from here.',
      'All regulated real estate services are carried out by a licensed representative. TKG Ventures makes the connection and stays alongside you through the process.',
    ],
    services: [
      { title: 'Properties for sale', body: 'Listings available through our licensed partners.' },
      {
        title: 'Buying assistance',
        body: 'Help defining your search, understanding the area and moving through offers.',
      },
      {
        title: 'Selling assistance',
        body: 'Preparation, pricing guidance and listing through a licensed representative.',
      },
      {
        title: 'Realtor connections',
        body: 'An introduction to a licensed realtor matched to your property type and area.',
      },
    ],
    audience: ['home', 'business'],
    audienceLine: 'Buying, selling and an introduction to a licensed realtor.',
    highlights: ['Licensed representation', 'Buy and sell support', 'Local market guidance'],
    theme: {
      accent: '#1F5CA8',
      accentInk: '#1B4C8A',
      accentSoft: '#E6EDF7',
      accentContrast: '#FFFFFF',
      accentBright: '#7FB6F2',
      glow: '#6FA3D8',
    },
    image: {
      src: '/divisions/real-estate.jpg',
      alt:
        'A contemporary house at dusk, warm light in its windows.',
    },
    scene: { shape: 'column' },
    notice: site.realEstateNotice,
    processTitle: 'How it works.',
    process: [
      {
        title: 'A conversation first',
        body: 'What you are trying to do, whether that is buying, selling or just understanding what your place is worth, and what your timeline looks like.',
      },
      {
        title: 'Matched to a licensed professional',
        body: 'We introduce you to a licensed real estate professional suited to your property type and area. All regulated work is theirs.',
      },
      {
        title: 'We stay alongside',
        body: 'Questions between appointments, coordinating a move, a clean, or a security install for the new place. That part is us.',
      },
    ],
    faqs: [
      {
        question: 'Is TKG Ventures a real estate brokerage?',
        answer:
          'No. TKG Ventures Ltd is not a licensed brokerage. Regulated real estate services, meaning listing, showing, negotiating and transacting, are carried out by licensed real estate professionals we introduce you to.',
      },
      {
        question: 'Does it cost me anything to be introduced?',
        answer:
          'No. Any fees for real estate services are agreed directly between you and the licensed professional, in writing, before any work starts.',
      },
      {
        question: 'Why go through you at all, then?',
        answer:
          'Because a move usually is not only a property transaction. The same company can coordinate the moving, cleaning, telecom setup and security install for the new place, so you have one number for all of it.',
      },
    ],
    form: {
      title: 'Real estate inquiry',
      intro: contactBlock('A licensed representative will handle any regulated services.'),
      submitLabel: 'Send real estate inquiry',
      disclaimer: site.realEstateNotice,
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'Are you buying or selling?',
          type: 'radio',
          required: true,
          options: [
            { value: 'buying', label: 'Buying' },
            { value: 'selling', label: 'Selling' },
            { value: 'both', label: 'Both' },
            { value: 'advice', label: 'Just want advice' },
          ],
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'detached', label: 'Detached house' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'land', label: 'Land' },
            { value: 'commercial', label: 'Commercial' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          name: 'area',
          label: 'Area or neighbourhood',
          type: 'text',
          required: true,
          span: 'half',
          placeholder: 'e.g. Surrey, Abbotsford',
        },
        {
          name: 'priceRange',
          label: 'Budget or expected price',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 700,000 - 900,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '1-3-months', label: '1-3 months' },
            { value: '3-6-months', label: '3-6 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Anything else we should know?',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Bedrooms, must-haves, current mortgage situation, or questions about the process.',
        },
      ],
    },
    seo: {
      title: 'Real Estate: buying, selling and licensed realtor connections',
      description:
        'Properties for sale, buying and selling assistance, and introductions to licensed realtors through TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 5 */
  {
    slug: 'moving-delivery',
    name: 'Moving & Delivery',
    shortName: 'Moving',
    tagline: 'Small moves, done properly',
    summary:
      'Pickup-truck moving, furniture and appliance delivery and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    body: [
      'Not every move needs a full moving company. A studio apartment, a couch, a fridge, a Marketplace pickup two cities over. Those jobs sit awkwardly between "do it yourself" and "book a crew". That is exactly the gap this division fills.',
      `We operate across the ${site.serviceArea.join(' and ')}. Give us the two addresses, a date and a rough list of what is moving, and we will come back with a price.`,
    ],
    services: [
      {
        title: 'Small & residential moves',
        body: 'Studio, one-bedroom and partial moves handled with a pickup truck and care.',
      },
      {
        title: 'Furniture & appliance delivery',
        body: 'Single-item delivery from store, warehouse or private seller to your door.',
      },
      {
        title: 'Marketplace pickups',
        body: 'We collect your online marketplace purchase and bring it to you.',
      },
      { title: 'Junk & load runs', body: 'Single-load removal and transport runs.' },
    ],
    audience: ['home', 'business'],
    audienceLine: 'Small moves, furniture delivery and Marketplace pickups.',
    highlights: [site.serviceArea.join(' & '), 'Single items to small moves', 'Flexible scheduling'],
    theme: {
      accent: '#9A6206',
      accentInk: '#7C4E05',
      accentSoft: '#FAEFD9',
      accentContrast: '#FFFFFF',
      accentBright: '#F0AE43',
      glow: '#D2A24F',
    },
    image: {
      src: '/divisions/moving-delivery.jpg',
      alt:
        'Stacked cardboard cartons on a pallet in a warehouse.',
    },
    scene: { shape: 'stack' },
    processTitle: 'Booked in four steps.',
    process: [
      {
        title: 'Send the details',
        body: 'Two addresses, a date, and a rough list of what is moving. A couple of photos help more than a long description.',
      },
      {
        title: 'Get a straight price',
        body: 'A quote for the job, not an hourly guess. If something is unusual, such as stairs, a piano or a tight timeline, it is priced in up front.',
      },
      {
        title: 'We turn up and move it',
        body: 'On time, with the right vehicle and straps, blankets and a dolly. Furniture is protected, not just carried.',
      },
      {
        title: 'Done, and paid for what was quoted',
        body: 'No surprise charges at the door. If the job matched the description, the price matches the quote.',
      },
    ],
    why: [
      {
        title: 'Sized for small moves',
        body: 'A studio, a one-bedroom, a single appliance. Jobs a full moving company overcharges for and a friend with a truck does badly.',
      },
      {
        title: 'Marketplace pickups, sorted',
        body: 'Bought a couch two cities away? Send us the listing and the address and we collect it, pay on your behalf if arranged, and deliver it.',
      },
      {
        title: 'Priced before we start',
        body: 'You know the number before the truck leaves. That is the whole point of quoting from a description and photos.',
      },
      {
        title: 'Across the whole region',
        body: 'Lower Mainland and Fraser Valley, both directions, including the awkward cross-region trips nobody else wants.',
      },
    ],
    faqs: [
      {
        question: 'What size of move can you handle?',
        answer:
          'Studio and one-bedroom moves, partial moves, and single items such as furniture, appliances and Marketplace pickups. For a full three-bedroom house we will tell you honestly that a larger crew is a better fit.',
      },
      {
        question: 'Do you supply packing materials?',
        answer:
          'We bring blankets, straps and a dolly for the move itself. Boxes and packing are on you unless you ask for them in the quote.',
      },
      {
        question: 'Can you pick something up and deliver it the same day?',
        answer:
          'Often, yes, if the addresses and timing work. Send the details and we will tell you the earliest slot.',
      },
      {
        question: 'Is anything not moved?',
        answer:
          'Hazardous materials, and anything that legally needs a licensed carrier. If in doubt, ask. The answer is usually a quick yes or no.',
      },
    ],
    form: {
      title: 'Moving & delivery quote',
      intro: contactBlock('Both addresses and a rough item list get you the fastest quote.'),
      submitLabel: 'Request moving quote',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'small-move', label: 'Small / residential move' },
            { value: 'furniture-delivery', label: 'Furniture or appliance delivery' },
            { value: 'marketplace-pickup', label: 'Marketplace pickup' },
            { value: 'single-item', label: 'Single item transport' },
            { value: 'junk-run', label: 'Junk / load run' },
          ],
        },
        {
          name: 'pickupAddress',
          label: 'Pickup address',
          type: 'address',
          required: true,
          span: 'half',
          placeholder: 'Start typing the address',
        },
        {
          name: 'dropoffAddress',
          label: 'Drop-off address',
          type: 'address',
          required: true,
          span: 'half',
          placeholder: 'Start typing the address',
        },
        { name: 'date', label: 'Preferred date', type: 'date', required: true, span: 'half' },
        {
          name: 'access',
          label: 'Access at either end',
          type: 'select',
          span: 'half',
          options: [
            { value: 'ground', label: 'Ground floor both ends' },
            { value: 'elevator', label: 'Elevator available' },
            { value: 'stairs', label: 'Stairs involved' },
            { value: 'unsure', label: 'Not sure yet' },
          ],
        },
        {
          name: 'items',
          label: 'What is being moved?',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'e.g. 3-seat sofa, queen bed frame + mattress, 8 boxes, fridge.',
        },
        PHOTO_FIELD({
          label: 'Photos of what is moving',
          help: 'Optional, and the single most useful thing you can send. A few photos of the rooms, the furniture and the doorway tell us the load size and the access far better than a list does, which is what lets us quote a price rather than an hourly guess.',
        }),
      ],
    },
    seo: {
      title: 'Moving & Delivery: small moves and furniture delivery',
      description:
        'Pickup-truck moving, furniture and appliance delivery, and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    },
  },

  /* ---------------------------------------------------------------- 6 */
  {
    slug: 'cleaning',
    name: 'Cleaning',
    shortName: 'Cleaning',
    tagline: 'Homes and workplaces, properly cleaned',
    summary:
      'Residential and commercial cleaning: regular contracts, one-off deep cleans, move-outs and post-construction.',
    body: [
      'We clean homes, offices, retail units, rentals between tenants and sites after the builders leave. The work is scoped against a written checklist, so "clean" means the same thing to you as it does to the person doing it.',
      'Everything starts from three things: the size of the space, how often it needs doing, and anything specific about it, such as a move-out standard, a post-renovation dust-down or products that have to be fragrance-free.',
    ],
    services: [
      {
        title: 'Residential cleaning',
        body: 'Regular, one-off, move-in and move-out cleans for homes and rentals.',
      },
      {
        title: 'Commercial cleaning',
        body: 'Offices, retail units and shared spaces on a schedule that suits the business.',
      },
      {
        title: 'Post-construction & turnover',
        body: 'Detailed cleans after building work or between tenancies.',
      },
      {
        title: 'Deep cleans',
        body: 'Appliances, inside cupboards, skirting and glass, the parts a maintenance visit does not reach.',
      },
    ],
    audience: ['home', 'business'],
    audienceLine: 'Regular, one-off, move-out and post-construction cleaning.',
    highlights: ['Residential & commercial', 'One-off or recurring', 'Written scope, checked'],
    theme: {
      accent: '#07786A',
      accentInk: '#065E53',
      accentSoft: '#DFF2EF',
      accentContrast: '#FFFFFF',
      accentBright: '#3FD9C0',
      glow: '#4FB3A3',
    },
    image: {
      src: '/divisions/cleaning.jpg',
      alt:
        'A bright, spotless living room with white furnishings.',
    },
    scene: { shape: 'ring' },
    processTitle: 'From first call to a spotless place.',
    process: [
      {
        title: 'Tell us the space and the schedule',
        body: 'Home or commercial, square footage, how often, and anything specific such as a move-out standard, post-renovation dust or allergies. Photos help.',
      },
      {
        title: 'We scope it',
        body: 'A clear checklist of what is included, so "clean" means the same thing to you and to the person doing it.',
      },
      {
        title: 'Cleaners who fit the job',
        body: 'Vetted, briefed, and matched to the work, because a deep clean and a weekly maintenance visit are not the same skill set.',
      },
      {
        title: 'Checked, and kept up',
        body: 'Regular work is inspected against the checklist. If something was missed, we fix it, not argue about it.',
      },
    ],
    why: [
      {
        title: 'Vetted people, not a gig app',
        body: 'Every cleaner is interviewed, reference-checked and briefed by us. You are not rolling dice on who walks in.',
      },
      {
        title: 'One-off or ongoing',
        body: 'Move-out cleans, post-construction, a single deep clean, or a weekly contract for an office. Same standard either way.',
      },
      {
        title: 'A checklist, in writing',
        body: 'The scope is agreed before the first visit, so the result can be checked against something concrete.',
      },
      {
        title: 'Continuity on contracts',
        body: 'Regular work goes to the same cleaner wherever we can. Someone who knows the space does a better job of it.',
      },
    ],
    faqs: [
      {
        question: 'Do you bring your own supplies?',
        answer:
          'Yes. Equipment and products are included, unless you have specific products you want used, which is fine too.',
      },
      {
        question: 'Are your cleaners insured and background-checked?',
        answer:
          'Cleaners are interviewed and reference-checked before they work for us. Ask us about insurance coverage for your specific job and we will tell you exactly what applies.',
      },
      {
        question: 'Can I get the same cleaner every time?',
        answer:
          'For regular contracts we aim for continuity, because a cleaner who knows the space does a better job. We cannot promise it every single visit, but it is the default.',
      },
      {
        question: 'Do you need me to be there?',
        answer:
          'Not necessarily. Plenty of customers leave a key, a lockbox code or building access instructions. Tell us which on the booking and we will work to it.',
      },
      {
        question: 'I need staff rather than a clean. Where do I go?',
        answer:
          'Our staffing division supplies cleaners and general labour to businesses running their own operation. That is a separate page. See Staffing.',
      },
    ],
    form: {
      title: 'Cleaning inquiry',
      intro: contactBlock('Space size and frequency are the two things we need most.'),
      submitLabel: 'Send cleaning inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'serviceType',
          label: 'What do you need?',
          type: 'radio',
          required: true,
          options: [
            { value: 'residential', label: 'Residential cleaning' },
            { value: 'commercial', label: 'Commercial cleaning' },
            { value: 'move-out', label: 'Move-in / move-out clean' },
            { value: 'post-construction', label: 'Post-construction / turnover' },
          ],
        },
        {
          name: 'frequency',
          label: 'Frequency',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'one-off', label: 'One-off' },
            { value: 'weekly', label: 'Weekly' },
            { value: 'biweekly', label: 'Every two weeks' },
            { value: 'monthly', label: 'Monthly' },
          ],
        },
        {
          name: 'size',
          label: 'Size of space',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 3 bed / 2 bath, or 2,500 sq ft office',
        },
        {
          name: 'address',
          label: 'Address of the property',
          type: 'address',
          required: true,
          span: 'half',
          placeholder: 'Start typing the address',
        },
        { name: 'startDate', label: 'Preferred start date', type: 'date', span: 'half' },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder: 'Access, supplies, hours of day, pets, special requirements.',
        },
        PHOTO_FIELD({
          label: 'Photos of the space',
          help: 'Optional. Photos of the rooms, and of anything that needs particular attention, let us quote the job accurately instead of estimating from the square footage.',
        }),
      ],
    },
    seo: {
      title: 'Cleaning: residential and commercial cleaning services',
      description:
        'Residential and commercial cleaning from TKG Ventures: regular contracts, one-off deep cleans, move-outs and post-construction cleans across the Lower Mainland and Fraser Valley.',
    },
  },

  /* ---------------------------------------------------------------- 7 */
  {
    slug: 'staffing',
    name: 'Staffing',
    shortName: 'Staffing',
    tagline: 'Vetted people, on site when you need them',
    summary:
      'Cleaning crews, general labour and support staff supplied to businesses that run their own operation.',
    body: [
      'Staffing is a different job from cleaning, and it is asked for by different people. Here you are not booking a service. You are asking for reliable people on your site, briefed and turning up, on your schedule and under your supervision.',
      'We interview and reference-check everyone we place, brief them on your site before the first shift, and cover short notice where we can. Tell us the role, the hours and the dates.',
    ],
    services: [
      {
        title: 'Cleaning staff supply',
        body: 'Cleaners placed with businesses that manage their own cleaning operation.',
      },
      {
        title: 'General labour',
        body: 'Reliable hands for warehouses, sites, loading and moving work.',
      },
      {
        title: 'Event & hospitality support',
        body: 'Short-notice cover for events, venues and hospitality shifts.',
      },
      {
        title: 'Ongoing placements',
        body: 'Longer-term staff for a recurring shift pattern, with cover arranged for absences.',
      },
    ],
    audience: ['business'],
    audienceLine: 'Vetted cleaners, general labour and short-notice cover for your site.',
    highlights: ['Interviewed & reference-checked', 'Short-notice cover', 'Ongoing or one shift'],
    theme: {
      accent: '#8A4BB0',
      accentInk: '#6F3B8F',
      accentSoft: '#F1E8F7',
      accentContrast: '#FFFFFF',
      accentBright: '#CDA0E8',
      glow: '#A97BC7',
    },
    image: {
      src: '/divisions/staffing.jpg',
      alt: 'A team at work in a bright commercial space.',
    },
    scene: { shape: 'people' },
    processTitle: 'From the role to the first shift.',
    process: [
      {
        title: 'Tell us the role',
        body: 'What the work actually involves, how many people, which hours and which dates. Certificates or clearances too, if the site needs them.',
      },
      {
        title: 'We match from a vetted pool',
        body: 'Everyone we place has been interviewed and reference-checked. We put forward people who have done the work, not whoever is free.',
      },
      {
        title: 'Briefed before they arrive',
        body: 'Site, access, supervisor, what "done" looks like. A first shift should not be spent explaining the basics.',
      },
      {
        title: 'Cover and continuity',
        body: 'For ongoing placements we keep the same people on the shift and arrange cover for absences rather than leaving you short.',
      },
    ],
    why: [
      {
        title: 'Vetted people, not a gig app',
        body: 'Interviewed, reference-checked and briefed by us. You know who is walking onto your site.',
      },
      {
        title: 'Short notice is normal here',
        body: 'A no-show, a sudden event, a spike in volume. Call and we will tell you honestly what we can cover and by when.',
      },
      {
        title: 'One shift or a standing rota',
        body: 'A single Saturday or a permanent weekday crew are both ordinary requests. There is no minimum you are locked into.',
      },
      {
        title: 'The same team runs its own crews',
        body: 'We staff our own cleaning and moving divisions daily, so the people we send you are held to a standard we depend on ourselves.',
      },
    ],
    faqs: [
      {
        question: 'What kinds of staff do you supply?',
        answer:
          'Cleaning crews, general labour, warehouse and loading help, and event or hospitality support. Tell us the role and the dates and we will tell you what we can cover.',
      },
      {
        question: 'How quickly can you fill a shift?',
        answer:
          'It depends on the role and the notice. Same-week is usual, and same-day is sometimes possible. We will give you a straight answer when you call rather than promising and cancelling.',
      },
      {
        question: 'Are the staff vetted?',
        answer:
          'Everyone is interviewed and reference-checked before we place them. Ask us about insurance and any clearances your site requires and we will tell you exactly what applies.',
      },
      {
        question: 'Who supervises them on site?',
        answer:
          'You do, for a supply placement. That is the difference between this and booking our cleaning service. If you would rather we managed the work and the result, use the Cleaning division instead.',
      },
      {
        question: 'Is there a minimum booking?',
        answer:
          'No fixed minimum. A single shift is a normal request, and so is an ongoing weekly rota. The rate depends on the role, the hours and the notice.',
      },
    ],
    form: {
      title: 'Staffing inquiry',
      intro: contactBlock('The role, the number of people and the dates get you the fastest answer.'),
      submitLabel: 'Send staffing inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'company',
          label: 'Company',
          type: 'text',
          required: true,
          span: 'half',
          autoComplete: 'organization',
          placeholder: 'Business name',
        },
        {
          name: 'roles',
          label: 'What roles do you need?',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'cleaning', label: 'Cleaning staff' },
            { value: 'general-labour', label: 'General labour' },
            { value: 'warehouse', label: 'Warehouse / loading' },
            { value: 'event', label: 'Event staff' },
            { value: 'hospitality', label: 'Hospitality' },
            { value: 'other', label: 'Something else' },
          ],
        },
        {
          name: 'headcount',
          label: 'How many people?',
          type: 'number',
          required: true,
          span: 'half',
          min: 1,
          max: 200,
          placeholder: 'e.g. 3',
        },
        {
          name: 'arrangement',
          label: 'Type of placement',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'one-shift', label: 'A single shift' },
            { value: 'short-term', label: 'Short term / a few weeks' },
            { value: 'ongoing', label: 'Ongoing rota' },
            { value: 'cover', label: 'Cover for absences' },
          ],
        },
        {
          name: 'schedule',
          label: 'Hours and days needed',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. Mon-Fri, 6am-10am',
        },
        { name: 'startDate', label: 'Start date', type: 'date', required: true, span: 'half' },
        {
          name: 'siteAddress',
          label: 'Site address',
          type: 'address',
          required: true,
          span: 'half',
          placeholder: 'Start typing the address',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'What the work involves, certificates or clearances required, supervision on site, and anything else we should know.',
        },
      ],
    },
    seo: {
      title: 'Staffing: cleaning crews, general labour and support staff',
      description:
        'Vetted cleaning staff, general labour, warehouse and event support supplied to businesses across the Lower Mainland and Fraser Valley by TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 8 */
  {
    slug: 'business-services',
    name: 'Business Services',
    shortName: 'Business',
    tagline: 'Opportunities, referrals and growth support',
    summary:
      'Business opportunities, businesses for sale, referrals, and support with marketing and lead generation.',
    body: [
      'This division is deliberately broad. It covers the work that does not fit neatly into the other divisions: businesses changing hands, opportunities worth looking at, introductions between people who should be talking, and help finding customers.',
      'If you are not sure which division your question belongs to, start here.',
    ],
    // "Business Services services" is what the shared heading would otherwise
    // produce. This division says what it does instead.
    servicesTitle: 'What we do',
    services: [
      { title: 'Businesses for sale', body: 'Operating businesses available through our network.' },
      { title: 'Business opportunities', body: 'Ventures and partnerships worth a conversation.' },
      {
        title: 'Referrals',
        body: 'Introductions to vetted providers inside and outside our divisions.',
      },
      {
        title: 'Lead generation',
        body: 'Drive growth with targeted outreach and expert sales strategies.',
      },
      {
        title: 'Brand strategy',
        body: 'Position your business for success with proven marketing solutions.',
      },
      {
        title: 'Market insights',
        body: 'Unlock actionable data to inform smarter business decisions.',
      },
      {
        title: 'Digital solutions',
        body: 'Custom software, SaaS and modern, responsive web design.',
      },
    ],
    audience: ['business'],
    audienceLine: 'Lead generation, brand and digital work, plus businesses for sale.',
    highlights: ['Lead generation and brand strategy', 'Software and web design', 'Referral network'],
    theme: {
      accent: '#4A7A1C',
      accentInk: '#3B6116',
      accentSoft: '#EEF4E2',
      accentContrast: '#FFFFFF',
      accentBright: '#A2DD5F',
      glow: '#86AC5C',
    },
    image: {
      src: '/divisions/business-services.jpg',
      alt:
        'An overhead view of a tidy desk with a laptop and notebook.',
    },
    scene: { shape: 'prism' },
    processTitle: 'How an engagement runs.',
    process: [
      {
        title: 'Discovery',
        body: 'What you sell, who buys it, what is working, and what you have already tried. An honest conversation, not a pitch.',
      },
      {
        title: 'A plan you can read',
        body: 'Specific, prioritised, with what it costs and what it should return. If we do not think we can move the number, we say so.',
      },
      {
        title: 'Execution',
        body: 'Lead generation, brand work and digital build: whichever pieces the plan calls for, delivered by the team that scoped it.',
      },
      {
        title: 'Measured, then adjusted',
        body: 'Results reported plainly against the plan, and the plan changed when the numbers say it should.',
      },
    ],
    why: [
      {
        title: 'We run sales teams ourselves',
        // Written out rather than interpolated: this string is built while the
        // `divisions` array is still being constructed, so it cannot read its
        // own length. Update it if a division is added.
        body: 'TKG Ventures sells across eight divisions every day. The advice comes from people doing it, not people who read about it.',
      },
      {
        title: 'Lead generation with a phone attached',
        body: 'Campaigns are built to produce conversations, and we have the appointment-setting team to follow them up.',
      },
      {
        title: 'Brand and digital in the same room',
        body: 'Positioning, identity and the website that carries them are planned together, so they do not contradict each other.',
      },
      {
        title: 'Scoped to your size',
        body: 'A one-person trade and a fifty-seat firm need different things. We do not sell the same package to both.',
      },
    ],
    faqs: [
      {
        question: 'What kind of businesses do you work with?',
        answer:
          'Mostly small and mid-sized local businesses in the Lower Mainland and Fraser Valley: trades, dealerships, professional services and retail. If you sell something and need more customers, that is the brief.',
      },
      {
        question: 'Do you do the work, or just advise?',
        answer:
          'Both. Strategy comes first, but the same team runs the campaigns, builds the digital assets and, if you want it, sets the appointments.',
      },
      {
        question: 'How do you charge?',
        answer:
          'By the engagement, scoped in writing after discovery. Ongoing work is a monthly arrangement with a clear scope; there is no minimum term you are locked into without knowing it.',
      },
      {
        question: 'Can you help a dealership or a security business specifically?',
        answer:
          'Yes. Those are two of our own divisions, so we know the customer journey and what actually converts in them.',
      },
    ],
    form: {
      title: 'Business services inquiry',
      intro: contactBlock('Tell us what you are working on and we will point you the right way.'),
      submitLabel: 'Send business inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'company',
          label: 'Company (optional)',
          type: 'text',
          span: 'half',
          autoComplete: 'organization',
        },
        {
          name: 'interest',
          label: 'What brings you here?',
          type: 'select',
          required: true,
          options: [
            { value: 'buy-business', label: 'Looking to buy a business' },
            { value: 'sell-business', label: 'Looking to sell a business' },
            { value: 'opportunity', label: 'Exploring an opportunity or partnership' },
            { value: 'referral', label: 'Looking for a referral' },
            { value: 'marketing', label: 'Marketing / lead generation' },
            { value: 'other', label: 'Something else' },
          ],
        },
        {
          name: 'industry',
          label: 'Industry or sector',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. food service, logistics',
        },
        {
          name: 'budget',
          label: 'Budget or investment range',
          type: 'text',
          span: 'half',
          placeholder: 'Optional',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder:
            'What you are trying to do, where you are in the process, and how we can help.',
        },
      ],
    },
    seo: {
      title: 'Business Services: opportunities, referrals and lead generation',
      description:
        'Business opportunities, businesses for sale, referrals and marketing support from TKG Ventures.',
    },
  },
];

/* ---------------------------------- helpers ---------------------------------- */

/**
 * How many divisions there are, spelled out.
 *
 * Copy that says "seven divisions" goes stale the moment one is added, and it
 * went stale exactly that way when Cleaning and Staffing were split. Anything
 * naming the count in a sentence should read it from here.
 */
const numberWords: Record<number, string> = {
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine',
  10: 'ten',
};

export const divisionCountWord: string = numberWords[divisions.length] ?? String(divisions.length);

export function getDivision(slug: string): Division | undefined {
  return divisions.find((d) => d.slug === slug);
}

export function divisionPath(slug: string): string {
  return `/services/${slug}`;
}
