import type { FormConfig } from '@/lib/form-schema';
import type { DivisionTheme } from '@/config/theme';
import { site } from '@/config/site';
import { SOURCING_DISCLAIMER } from '@/config/automotive';

/* =========================================================================
   THE ONLY FILE YOU EDIT TO ADD A DIVISION.

   Navigation, the homepage grid, the 3D scroll beats, /services/[division]
   routing, the inquiry form, metadata and sitemap.xml all render from this
   array. See README.md > "Adding a division".
   ========================================================================= */

export interface DivisionService {
  title: string;
  body: string;
}

export interface Division {
  /** URL segment: /services/<slug> */
  slug: string;
  /** Full name, used in headings and metadata. */
  name: string;
  /** Compact name for nav and cards. */
  shortName: string;
  /** One line, sentence case, no period. */
  tagline: string;
  /** 1-2 sentences under the H1. */
  summary: string;
  /** Body copy, one string per paragraph. */
  body: string[];
  /** Rendered as the "What we do" list. */
  services: DivisionService[];
  /** Short trust / at-a-glance points. */
  highlights: string[];
  /**
   * The division's colour, used everywhere at once: the card, the page hero,
   * the form focus ring, the active rail tick and the 3D slab's edge glow.
   * Verified for WCAG AA by `node scripts/check-contrast.mjs`.
   */
  theme: DivisionTheme;
  /**
   * The division's artwork. Generated by
   * `node scripts/generate-division-images.mjs`; swap the file at `src` for
   * real photography without touching any component. See README > Imagery.
   */
  image: { src: string; alt: string };
  /** The geometry archetype for this division's 3D scroll moment. */
  scene: {
    shape: 'slab' | 'ring' | 'prism' | 'lattice' | 'column' | 'arc' | 'stack';
  };
  /** Optional legal/regulatory notice rendered prominently on the page. */
  notice?: string;
  /** "How it works" steps. Optional; the section hides when absent. */
  process?: { title: string; body: string }[];
  /** Heading over the process section. Defaults to "Start to finish." */
  processTitle?: string;
  /** "Why us" points. Optional; the section hides when absent. */
  why?: { title: string; body: string }[];
  /** FAQs, rendered as an accordion with FAQPage JSON-LD. Optional. */
  faqs?: { question: string; answer: string }[];
  form: FormConfig;
  seo: { title: string; description: string };
}

const contactBlock = (extra = ''): string =>
  `Tell us what you need and we will come back with next steps.${extra ? ` ${extra}` : ''}`;

export const divisions: Division[] = [
  /* ---------------------------------------------------------------- 1 */
  {
    slug: 'security-smart-home',
    name: 'Security & Smart Home',
    shortName: 'Security',
    tagline: 'Alarms, cameras and connected homes',
    summary:
      'Alarm systems, cameras, video doorbells and smart-home equipment - supplied, installed and serviced.',
    body: [
      'A security setup only works if it is specified for the actual building and the people in it. We look at the property, recommend equipment that fits, install it properly and stay available when something needs adjusting.',
      'The same team handles smart-home equipment, so lighting, locks, thermostats and cameras end up on one coherent setup rather than five apps that do not talk to each other.',
    ],
    services: [
      {
        title: 'Smart systems',
        body: 'Protect your property with advanced automation and monitoring.',
      },
      {
        title: '24/7 monitoring',
        body: 'Reliable, real-time security for peace of mind.',
      },
      {
        title: 'Cameras & doorbells',
        body: 'Camera placement, video doorbells and recording setup for homes and businesses.',
      },
      {
        title: 'Smart-home equipment',
        body: 'Smart locks, lighting, thermostats and hubs configured to work together.',
      },
      {
        title: 'Installation',
        body: 'Professional setup for seamless, secure home integration.',
      },
    ],
    highlights: [
      'Authorized Brinks Home Security dealer',
      '24/7 monitoring',
      'Professional installation',
    ],
    theme: {
      accent: '#5A3FC0',
      accentInk: '#4A3399',
      accentSoft: '#EDE9F9',
      accentContrast: '#FFFFFF',
      accentBright: '#B39CFA',
      glow: '#9182D4',
    },
    image: {
      src: '/divisions/security-smart-home.jpg',
      alt:
        'A smart-home sensor lit in blue and magenta.',
    },
    scene: { shape: 'lattice' },
    notice:
      'TKG Ventures Ltd is an authorized dealer of Brinks Home Security, delivering professional home security and smart automation solutions across select markets.',
    form: {
      title: 'Security & smart home inquiry',
      intro: contactBlock('Tell us about the property and what you want covered.'),
      submitLabel: 'Send security inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'house', label: 'House' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'retail', label: 'Retail unit' },
            { value: 'office', label: 'Office' },
            { value: 'warehouse', label: 'Warehouse / industrial' },
          ],
        },
        {
          name: 'systems',
          label: 'What are you interested in?',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'alarm', label: 'Alarm system' },
            { value: 'cameras', label: 'Security cameras' },
            { value: 'doorbell', label: 'Video doorbell' },
            { value: 'locks', label: 'Smart locks' },
            { value: 'lighting', label: 'Smart lighting' },
            { value: 'thermostat', label: 'Smart thermostat' },
          ],
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'new-install', label: 'New installation' },
            { value: 'upgrade', label: 'Upgrade existing system' },
            { value: 'service', label: 'Service or repair' },
            { value: 'equipment-only', label: 'Equipment purchase only' },
          ],
        },
        {
          name: 'address',
          label: 'Service address',
          type: 'text',
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Number of entry points, existing equipment, coverage areas, monitoring preference.',
        },
      ],
    },
    seo: {
      title: 'Security & Smart Home - alarms, cameras and installation',
      description:
        'Alarm systems, security cameras, video doorbells and smart-home equipment. Supply, installation and service from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 2 */
  {
    slug: 'telecommunications',
    name: 'Telecommunications',
    shortName: 'Telecom',
    tagline: 'Internet, TV and phone, without the runaround',
    summary: 'Internet, television and phone plans - compared, explained and set up.',
    body: [
      'Telecom pricing is deliberately hard to compare. This division does the comparing for you: what is actually available at your address, what the real monthly cost looks like after promotional periods, and whether switching is worth the effort.',
      'We handle home and business connections, new installs and switches from an existing provider.',
    ],
    services: [
      {
        title: 'Internet',
        body: 'Home and business internet plans matched to how you actually use the connection.',
      },
      { title: 'Television', body: 'TV packages and streaming alternatives, compared honestly.' },
      { title: 'Phone', body: 'Home phone and mobile plans, including business lines.' },
      {
        title: 'Offers & switching',
        body: 'Current promotions and help moving from your existing provider.',
      },
    ],
    highlights: ['Home & business', 'Plan comparison', 'Switching support'],
    theme: {
      accent: '#08718F',
      accentInk: '#065A72',
      accentSoft: '#DEF0F6',
      accentContrast: '#FFFFFF',
      accentBright: '#4FCBEB',
      glow: '#46A9C6',
    },
    image: {
      src: '/divisions/telecommunications.jpg',
      alt:
        'Illuminated fibre-optic strands against a black background.',
    },
    scene: { shape: 'arc' },
    processTitle: 'Signed up in four steps.',
    process: [
      {
        title: 'Tell us what you have',
        body: 'Your address, what you are paying now, and what actually annoys you about it - speed, price, the TV package, the contract.',
      },
      {
        title: 'We compare the real options',
        body: 'The plans available at your address, with the promotional price and the price it becomes afterwards side by side.',
      },
      {
        title: 'You pick, we set it up',
        body: 'We place the order, book the installation or arrange the self-install kit, and handle the cancellation of the old service.',
      },
      {
        title: 'One number afterwards',
        body: 'Billing question, outage, upgrade - you call us and we deal with the provider, rather than you sitting in their queue.',
      },
    ],
    why: [
      {
        title: 'Every provider, one conversation',
        body: 'We are not tied to a single carrier. The recommendation is the plan that fits, not the one paying the biggest commission this month.',
      },
      {
        title: 'The price after the promo, in writing',
        body: 'Introductory pricing is where most telecom regret comes from. We show both numbers before you sign anything.',
      },
      {
        title: 'Business lines too',
        body: 'Multi-line phone, business internet with a static IP, and the paperwork that comes with moving an office.',
      },
      {
        title: 'Local, and answerable',
        body: 'The same person who signed you up is the person who picks up when something goes wrong.',
      },
    ],
    faqs: [
      {
        question: 'Do I pay extra for going through you?',
        answer:
          'No. You pay the provider the same plan price you would pay direct. We are compensated by the provider for the signup, which is why we say the recommendation is the plan that fits rather than the one that pays the most.',
      },
      {
        question: 'Can you get me out of my current contract?',
        answer:
          'Sometimes. It depends on the provider and how far in you are. We will tell you the real cancellation cost before you switch, and whether a new provider will cover part of it.',
      },
      {
        question: 'How long does a switch take?',
        answer:
          'Internet and TV are typically live within a few days of ordering, depending on installation availability in your building. Phone number transfers usually take a couple of business days.',
      },
      {
        question: 'Do you handle business accounts?',
        answer:
          'Yes - business internet, multi-line phone systems and TV for waiting rooms and hospitality. Tell us how many lines and seats and we will come back with options.',
      },
    ],
    form: {
      title: 'Telecommunications inquiry',
      intro: contactBlock('Your address determines what is actually available.'),
      submitLabel: 'Send telecom inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'accountType',
          label: 'Home or business?',
          type: 'radio',
          required: true,
          options: [
            { value: 'home', label: 'Home' },
            { value: 'business', label: 'Business' },
          ],
        },
        {
          name: 'services',
          label: 'Services you want',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'internet', label: 'Internet' },
            { value: 'tv', label: 'TV' },
            { value: 'home-phone', label: 'Home phone' },
            { value: 'mobile', label: 'Mobile' },
          ],
        },
        {
          name: 'address',
          label: 'Service address',
          type: 'text',
          required: true,
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'currentProvider',
          label: 'Current provider (if any)',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. none',
        },
        {
          name: 'details',
          label: 'What matters most?',
          type: 'textarea',
          rows: 4,
          placeholder:
            'Speed, price, contract length, number of users, channels you actually watch.',
        },
      ],
    },
    seo: {
      title: 'Telecommunications - internet, TV and phone plans',
      description:
        'Internet, television and phone plans for home and business, compared and set up by TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 3 */
  {
    slug: 'automotive',
    name: 'Automotive',
    shortName: 'Automotive',
    tagline: 'We find the car. You choose it.',
    summary:
      'A personal vehicle sourcing service: tell us what you are looking for, and we search our dealership network on your behalf.',
    body: [
'This division is a concierge, not a car lot. We hold no inventory and we are not a licensed dealership. What we do is take your requirements, search the dealerships we work with, and come back with vehicles that actually match - then introduce you to the dealer holding the one you want.',
      'The same works in reverse. If you are selling, we put the vehicle in front of buyers and dealership partners rather than leaving you to field messages from strangers.',
    ],
    services: [
      {
        title: 'Vehicle sourcing',
        body: 'Tell us the make, model, budget and timeline. We search our dealership network on your behalf and bring back a shortlist.',
      },
      {
        title: 'Dealer introductions',
        body: 'We introduce you to the licensed dealership selling the vehicle you choose, and stay involved through to handover.',
      },
      {
        title: 'Selling assistance',
        body: 'Help preparing and pricing a vehicle you want to move, and connecting you with a buyer or dealership partner.',
      },
      {
        title: 'Inspection coordination',
        body: 'Arranging pre-purchase inspection and servicing before you commit.',
      },
      {
        title: 'Solutions for dealerships',
        body: 'Lead generation and digital support for the dealership partners we source through.',
      },
    ],
    highlights: [
      'Sourced to your exact specification',
      'Searched across a network of licensed dealerships',
      'No inventory, no lot, no pressure to take what is in stock',
    ],
    theme: {
      accent: '#BC4A17',
      accentInk: '#96380F',
      accentSoft: '#FBEBE2',
      accentContrast: '#FFFFFF',
      accentBright: '#FF9163',
      glow: '#FF8A4C',
    },
    image: {
      src: '/divisions/automotive.jpg',
      alt:
        'A line of dark vehicles parked under low showroom lighting.',
    },
    scene: { shape: 'slab' },
    notice: SOURCING_DISCLAIMER,
    form: {
      title: 'Automotive inquiry',
      intro: contactBlock('The more detail on the vehicle, the faster we can help.'),
      submitLabel: 'Send automotive inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'What do you need?',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'buying', label: 'I am looking to buy' },
            { value: 'selling', label: 'I am looking to sell' },
            { value: 'sourcing', label: 'Find a specific vehicle for me' },
            { value: 'service', label: 'Servicing or inspection' },
          ],
        },
        {
          name: 'vehicle',
          label: 'Make / model of interest',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. Toyota RAV4, 2019+',
        },
        {
          name: 'budget',
          label: 'Budget range',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 18,000 - 25,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '2-4-weeks', label: 'Within 2-4 weeks' },
            { value: '1-3-months', label: '1-3 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'Condition, mileage, trim, financing needs, or anything else that helps.',
        },
      ],
    },
    seo: {
      title: 'Automotive - personal vehicle sourcing',
      description:
        'Tell us what you are looking for and we search our dealership network on your behalf. Vehicle sourcing, dealer introductions and selling assistance from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 4 */
  {
    slug: 'real-estate',
    name: 'Real Estate',
    shortName: 'Real Estate',
    tagline: 'Connected to licensed representation',
    summary: 'Properties for sale, buy and sell assistance, and introductions to licensed realtors.',
    body: [
      'Property decisions are rarely just about the property. Our real estate division helps you get oriented: what is on the market, what your place might be worth, and what the process actually looks like from here.',
      'All regulated real estate services are carried out by a licensed representative. TKG Ventures makes the connection and stays alongside you through the process.',
    ],
    services: [
      { title: 'Properties for sale', body: 'Listings available through our licensed partners.' },
      {
        title: 'Buying assistance',
        body: 'Help defining your search, understanding the area and moving through offers.',
      },
      {
        title: 'Selling assistance',
        body: 'Preparation, pricing guidance and listing through a licensed representative.',
      },
      {
        title: 'Realtor connections',
        body: 'An introduction to a licensed realtor matched to your property type and area.',
      },
    ],
    highlights: ['Licensed representation', 'Buy and sell support', 'Local market guidance'],
    theme: {
      accent: '#1F5CA8',
      accentInk: '#1B4C8A',
      accentSoft: '#E6EDF7',
      accentContrast: '#FFFFFF',
      accentBright: '#7FB6F2',
      glow: '#6FA3D8',
    },
    image: {
      src: '/divisions/real-estate.jpg',
      alt:
        'A contemporary house at dusk, warm light in its windows.',
    },
    scene: { shape: 'column' },
    notice: site.realEstateNotice,
    processTitle: 'How it works.',
    process: [
      {
        title: 'A conversation first',
        body: 'What you are trying to do - buy, sell, or just understand what your place is worth - and what your timeline looks like.',
      },
      {
        title: 'Matched to a licensed professional',
        body: 'We introduce you to a licensed real estate professional suited to your property type and area. All regulated work is theirs.',
      },
      {
        title: 'We stay alongside',
        body: 'Questions between appointments, coordinating a move, a clean, or a security install for the new place - that part is us.',
      },
    ],
    faqs: [
      {
        question: 'Is TKG Ventures a real estate brokerage?',
        answer:
          'No. TKG Ventures Ltd is not a licensed brokerage. Regulated real estate services - listing, showing, negotiating, transacting - are carried out by licensed real estate professionals we introduce you to.',
      },
      {
        question: 'Does it cost me anything to be introduced?',
        answer:
          'No. Any fees for real estate services are agreed directly between you and the licensed professional, in writing, before any work starts.',
      },
      {
        question: 'Why go through you at all, then?',
        answer:
          'Because a move usually is not only a property transaction. The same company can coordinate the moving, cleaning, telecom setup and security install for the new place, so you have one number for all of it.',
      },
    ],
    form: {
      title: 'Real estate inquiry',
      intro: contactBlock('A licensed representative will handle any regulated services.'),
      submitLabel: 'Send real estate inquiry',
      disclaimer: site.realEstateNotice,
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'Are you buying or selling?',
          type: 'radio',
          required: true,
          options: [
            { value: 'buying', label: 'Buying' },
            { value: 'selling', label: 'Selling' },
            { value: 'both', label: 'Both' },
            { value: 'advice', label: 'Just want advice' },
          ],
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'detached', label: 'Detached house' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'land', label: 'Land' },
            { value: 'commercial', label: 'Commercial' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          name: 'area',
          label: 'Area or neighbourhood',
          type: 'text',
          required: true,
          span: 'half',
          placeholder: 'e.g. Surrey, Abbotsford',
        },
        {
          name: 'priceRange',
          label: 'Budget or expected price',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 700,000 - 900,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '1-3-months', label: '1-3 months' },
            { value: '3-6-months', label: '3-6 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Anything else we should know?',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Bedrooms, must-haves, current mortgage situation, or questions about the process.',
        },
      ],
    },
    seo: {
      title: 'Real Estate - buying, selling and licensed realtor connections',
      description:
        'Properties for sale, buying and selling assistance, and introductions to licensed realtors through TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 5 */
  {
    slug: 'moving-delivery',
    name: 'Moving & Delivery',
    shortName: 'Moving',
    tagline: 'Small moves, done properly',
    summary:
      'Pickup-truck moving, furniture and appliance delivery and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    body: [
      'Not every move needs a full moving company. A studio apartment, a couch, a fridge, a Marketplace pickup two cities over - those jobs sit awkwardly between "do it yourself" and "book a crew". That is exactly the gap this division fills.',
      `We operate across the ${site.serviceArea.join(' and ')}. Give us the two addresses, a date and a rough list of what is moving, and we will come back with a price.`,
    ],
    services: [
      {
        title: 'Small & residential moves',
        body: 'Studio, one-bedroom and partial moves handled with a pickup truck and care.',
      },
      {
        title: 'Furniture & appliance delivery',
        body: 'Single-item delivery from store, warehouse or private seller to your door.',
      },
      {
        title: 'Marketplace pickups',
        body: 'We collect your online marketplace purchase and bring it to you.',
      },
      { title: 'Junk & load runs', body: 'Single-load removal and transport runs.' },
    ],
    highlights: [site.serviceArea.join(' & '), 'Single items to small moves', 'Flexible scheduling'],
    theme: {
      accent: '#9A6206',
      accentInk: '#7C4E05',
      accentSoft: '#FAEFD9',
      accentContrast: '#FFFFFF',
      accentBright: '#F0AE43',
      glow: '#D2A24F',
    },
    image: {
      src: '/divisions/moving-delivery.jpg',
      alt:
        'Stacked cardboard cartons on a pallet in a warehouse.',
    },
    scene: { shape: 'stack' },
    processTitle: 'Booked in four steps.',
    process: [
      {
        title: 'Send the details',
        body: 'Two addresses, a date, and a rough list of what is moving. A couple of photos help more than a long description.',
      },
      {
        title: 'Get a straight price',
        body: 'A quote for the job, not an hourly guess. If something is unusual - stairs, a piano, a tight timeline - it is priced in up front.',
      },
      {
        title: 'We turn up and move it',
        body: 'On time, with the right vehicle and straps, blankets and a dolly. Furniture is protected, not just carried.',
      },
      {
        title: 'Done, and paid for what was quoted',
        body: 'No surprise charges at the door. If the job matched the description, the price matches the quote.',
      },
    ],
    why: [
      {
        title: 'Sized for small moves',
        body: 'A studio, a one-bedroom, a single appliance. Jobs a full moving company overcharges for and a friend with a truck does badly.',
      },
      {
        title: 'Marketplace pickups, sorted',
        body: 'Bought a couch two cities away? Send us the listing and the address and we collect it, pay on your behalf if arranged, and deliver it.',
      },
      {
        title: 'Priced before we start',
        body: 'You know the number before the truck leaves. That is the whole point of quoting from a description and photos.',
      },
      {
        title: 'Across the whole region',
        body: 'Lower Mainland and Fraser Valley, both directions, including the awkward cross-region trips nobody else wants.',
      },
    ],
    faqs: [
      {
        question: 'What size of move can you handle?',
        answer:
          'Studio and one-bedroom moves, partial moves, and single items - furniture, appliances, Marketplace pickups. For a full three-bedroom house we will tell you honestly that a larger crew is a better fit.',
      },
      {
        question: 'Do you supply packing materials?',
        answer:
          'We bring blankets, straps and a dolly for the move itself. Boxes and packing are on you unless you ask for them in the quote.',
      },
      {
        question: 'Can you pick something up and deliver it the same day?',
        answer:
          'Often, yes, if the addresses and timing work. Send the details and we will tell you the earliest slot.',
      },
      {
        question: 'Is anything not moved?',
        answer:
          'Hazardous materials, and anything that legally needs a licensed carrier. If in doubt, ask - the answer is usually a quick yes or no.',
      },
    ],
    form: {
      title: 'Moving & delivery quote',
      intro: contactBlock('Both addresses and a rough item list get you the fastest quote.'),
      submitLabel: 'Request moving quote',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'small-move', label: 'Small / residential move' },
            { value: 'furniture-delivery', label: 'Furniture or appliance delivery' },
            { value: 'marketplace-pickup', label: 'Marketplace pickup' },
            { value: 'single-item', label: 'Single item transport' },
            { value: 'junk-run', label: 'Junk / load run' },
          ],
        },
        {
          name: 'pickupAddress',
          label: 'Pickup address',
          type: 'text',
          required: true,
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'dropoffAddress',
          label: 'Drop-off address',
          type: 'text',
          required: true,
          span: 'half',
          placeholder: 'Street, city',
        },
        { name: 'date', label: 'Preferred date', type: 'date', required: true, span: 'half' },
        {
          name: 'access',
          label: 'Access at either end',
          type: 'select',
          span: 'half',
          options: [
            { value: 'ground', label: 'Ground floor both ends' },
            { value: 'elevator', label: 'Elevator available' },
            { value: 'stairs', label: 'Stairs involved' },
            { value: 'unsure', label: 'Not sure yet' },
          ],
        },
        {
          name: 'items',
          label: 'What is being moved?',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'e.g. 3-seat sofa, queen bed frame + mattress, 8 boxes, fridge.',
        },
      ],
    },
    seo: {
      title: 'Moving & Delivery - small moves and furniture delivery',
      description:
        'Pickup-truck moving, furniture and appliance delivery, and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    },
  },

  /* ---------------------------------------------------------------- 6 */
  {
    slug: 'cleaning-staffing',
    name: 'Cleaning & Staffing',
    shortName: 'Cleaning',
    tagline: 'Clean spaces and the people to keep them that way',
    summary:
      'Residential and commercial cleaning, plus cleaning staff supplied to businesses that need their own team.',
    body: [
      'Two related things happen in this division. We clean - homes, offices, units between tenants, sites after a job. And we supply cleaning staff to businesses that would rather have their own consistent team on site.',
      'Whichever you need, the starting point is the same: the size of the space, how often it needs doing, and any specific requirements.',
    ],
    services: [
      {
        title: 'Residential cleaning',
        body: 'Regular, one-off, move-in and move-out cleans for homes and rentals.',
      },
      {
        title: 'Commercial cleaning',
        body: 'Offices, retail units and shared spaces on a schedule that suits the business.',
      },
      {
        title: 'Staff supply',
        body: 'Cleaning staff and manpower supplied to businesses that manage their own operation.',
      },
      {
        title: 'Post-construction & turnover',
        body: 'Detailed cleans after building work or between tenancies.',
      },
    ],
    highlights: ['Residential & commercial', 'One-off or recurring', 'Staff supply available'],
    theme: {
      accent: '#07786A',
      accentInk: '#065E53',
      accentSoft: '#DFF2EF',
      accentContrast: '#FFFFFF',
      accentBright: '#3FD9C0',
      glow: '#4FB3A3',
    },
    image: {
      src: '/divisions/cleaning-staffing.jpg',
      alt:
        'A bright, spotless living room with white furnishings.',
    },
    scene: { shape: 'ring' },
    processTitle: 'From first call to a spotless place.',
    process: [
      {
        title: 'Tell us the space and the schedule',
        body: 'Home or commercial, square footage, how often, and anything specific - move-out standard, post-renovation, allergies.',
      },
      {
        title: 'We scope it',
        body: 'A clear checklist of what is included, so "clean" means the same thing to you and to the person doing it.',
      },
      {
        title: 'Staff who fit the job',
        body: 'Vetted, briefed, and matched to the work - a deep clean and a weekly maintenance visit are not the same skill set.',
      },
      {
        title: 'Checked, and kept up',
        body: 'Regular work is inspected against the checklist. If something was missed, we fix it, not argue about it.',
      },
    ],
    why: [
      {
        title: 'Vetted people, not a gig app',
        body: 'Every cleaner and staff member is interviewed, reference-checked and briefed by us. You are not rolling dice on who walks in.',
      },
      {
        title: 'One-off or ongoing',
        body: 'Move-out cleans, post-construction, a single deep clean - or a weekly contract for an office. Same standard either way.',
      },
      {
        title: 'Staffing beyond cleaning',
        body: 'Reliable general labour and short-notice cover for events, warehouses and hospitality, from the same vetted pool.',
      },
      {
        title: 'A checklist, in writing',
        body: 'The scope is agreed before the first visit, so the result can be checked against something concrete.',
      },
    ],
    faqs: [
      {
        question: 'Do you bring your own supplies?',
        answer:
          'Yes for cleaning - equipment and products are included unless you have specific products you want used, which is fine too.',
      },
      {
        question: 'Are your staff insured and background-checked?',
        answer:
          'Staff are interviewed and reference-checked before they work for us. Ask us about insurance coverage for your specific job and we will tell you exactly what applies.',
      },
      {
        question: 'Can I get the same cleaner every time?',
        answer:
          'For regular contracts we aim for continuity, because a cleaner who knows the space does a better job. We cannot promise it every single visit, but it is the default.',
      },
      {
        question: 'What kind of staffing do you provide?',
        answer:
          'General labour, event staff, warehouse and hospitality support, and cleaning crews - typically short-term or short-notice. Tell us the role and the dates.',
      },
    ],
    form: {
      title: 'Cleaning & staffing inquiry',
      intro: contactBlock('Space size and frequency are the two things we need most.'),
      submitLabel: 'Send cleaning inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'serviceType',
          label: 'What do you need?',
          type: 'radio',
          required: true,
          options: [
            { value: 'residential', label: 'Residential cleaning' },
            { value: 'commercial', label: 'Commercial cleaning' },
            { value: 'staffing', label: 'Cleaning staff supply' },
            { value: 'post-construction', label: 'Post-construction / turnover' },
          ],
        },
        {
          name: 'frequency',
          label: 'Frequency',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'one-off', label: 'One-off' },
            { value: 'weekly', label: 'Weekly' },
            { value: 'biweekly', label: 'Every two weeks' },
            { value: 'monthly', label: 'Monthly' },
            { value: 'ongoing-staff', label: 'Ongoing staff placement' },
          ],
        },
        {
          name: 'size',
          label: 'Size of space',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 3 bed / 2 bath, or 2,500 sq ft office',
        },
        {
          name: 'address',
          label: 'Location',
          type: 'text',
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'City or full address',
        },
        { name: 'startDate', label: 'Preferred start date', type: 'date', span: 'half' },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Access, supplies, hours of day, number of staff needed, special requirements.',
        },
      ],
    },
    seo: {
      title: 'Cleaning & Staffing - residential, commercial and staff supply',
      description:
        'Residential and commercial cleaning plus supplied cleaning staff and manpower from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 7 */
  {
    slug: 'business-services',
    name: 'Business Services',
    shortName: 'Business',
    tagline: 'Opportunities, referrals and growth support',
    summary:
      'Business opportunities, businesses for sale, referrals, and marketing and lead generation support.',
    body: [
      'This division is deliberately broad. It covers the work that does not fit neatly into the other six: businesses changing hands, opportunities worth looking at, introductions between people who should be talking, and help finding customers.',
      'If you are not sure which division your question belongs to, start here.',
    ],
    services: [
      { title: 'Businesses for sale', body: 'Operating businesses available through our network.' },
      { title: 'Business opportunities', body: 'Ventures and partnerships worth a conversation.' },
      {
        title: 'Referrals',
        body: 'Introductions to vetted providers inside and outside our divisions.',
      },
      {
        title: 'Lead generation',
        body: 'Drive growth with targeted outreach and expert sales strategies.',
      },
      {
        title: 'Brand strategy',
        body: 'Position your business for success with proven marketing solutions.',
      },
      {
        title: 'Market insights',
        body: 'Unlock actionable data to inform smarter business decisions.',
      },
      {
        title: 'Digital solutions',
        body: 'Custom software, SaaS and modern, responsive web design.',
      },
    ],
    highlights: ['Lead generation and brand strategy', 'Software and web design', 'Referral network'],
    theme: {
      accent: '#4A7A1C',
      accentInk: '#3B6116',
      accentSoft: '#EEF4E2',
      accentContrast: '#FFFFFF',
      accentBright: '#A2DD5F',
      glow: '#86AC5C',
    },
    image: {
      src: '/divisions/business-services.jpg',
      alt:
        'An overhead view of a tidy desk with a laptop and notebook.',
    },
    scene: { shape: 'prism' },
    processTitle: 'How an engagement runs.',
    process: [
      {
        title: 'Discovery',
        body: 'What you sell, who buys it, what is working, and what you have already tried. An honest conversation, not a pitch.',
      },
      {
        title: 'A plan you can read',
        body: 'Specific, prioritised, with what it costs and what it should return. If we do not think we can move the number, we say so.',
      },
      {
        title: 'Execution',
        body: 'Lead generation, brand work, digital build - whichever pieces the plan calls for, delivered by the team that scoped it.',
      },
      {
        title: 'Measured, then adjusted',
        body: 'Results reported plainly against the plan, and the plan changed when the numbers say it should.',
      },
    ],
    why: [
      {
        title: 'We run sales teams ourselves',
        body: 'TKG Ventures sells across seven divisions every day. The advice comes from people doing it, not people who read about it.',
      },
      {
        title: 'Lead generation with a phone attached',
        body: 'Campaigns are built to produce conversations, and we have the appointment-setting team to follow them up.',
      },
      {
        title: 'Brand and digital in the same room',
        body: 'Positioning, identity and the website that carries them are planned together, so they do not contradict each other.',
      },
      {
        title: 'Scoped to your size',
        body: 'A one-person trade and a fifty-seat firm need different things. We do not sell the same package to both.',
      },
    ],
    faqs: [
      {
        question: 'What kind of businesses do you work with?',
        answer:
          'Mostly small and mid-sized local businesses in the Lower Mainland and Fraser Valley - trades, dealerships, professional services, retail. If you sell something and need more customers, that is the brief.',
      },
      {
        question: 'Do you do the work, or just advise?',
        answer:
          'Both. Strategy comes first, but the same team runs the campaigns, builds the digital assets and, if you want it, sets the appointments.',
      },
      {
        question: 'How do you charge?',
        answer:
          'By the engagement, scoped in writing after discovery. Ongoing work is a monthly arrangement with a clear scope; there is no minimum term you are locked into without knowing it.',
      },
      {
        question: 'Can you help a dealership or a security business specifically?',
        answer:
          'Yes - those are two of our own divisions, so we know the customer journey and what actually converts in them.',
      },
    ],
    form: {
      title: 'Business services inquiry',
      intro: contactBlock('Tell us what you are working on and we will point you the right way.'),
      submitLabel: 'Send business inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'company',
          label: 'Company (optional)',
          type: 'text',
          span: 'half',
          autoComplete: 'organization',
        },
        {
          name: 'interest',
          label: 'What brings you here?',
          type: 'select',
          required: true,
          options: [
            { value: 'buy-business', label: 'Looking to buy a business' },
            { value: 'sell-business', label: 'Looking to sell a business' },
            { value: 'opportunity', label: 'Exploring an opportunity or partnership' },
            { value: 'referral', label: 'Looking for a referral' },
            { value: 'marketing', label: 'Marketing / lead generation' },
            { value: 'other', label: 'Something else' },
          ],
        },
        {
          name: 'industry',
          label: 'Industry or sector',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. food service, logistics',
        },
        {
          name: 'budget',
          label: 'Budget or investment range',
          type: 'text',
          span: 'half',
          placeholder: 'Optional',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder:
            'What you are trying to do, where you are in the process, and how we can help.',
        },
      ],
    },
    seo: {
      title: 'Business Services - opportunities, referrals and lead generation',
      description:
        'Business opportunities, businesses for sale, referrals and marketing support from TKG Ventures.',
    },
  },
];

/* ---------------------------------- helpers ---------------------------------- */

export const divisionSlugs: string[] = divisions.map((d) => d.slug);

export function getDivision(slug: string): Division | undefined {
  return divisions.find((d) => d.slug === slug);
}

export function divisionPath(slug: string): string {
  return `/services/${slug}`;
}
