import type { FormConfig } from '@/lib/form-schema';
import type { DivisionTheme } from '@/config/theme';
import { site } from '@/config/site';

/* =========================================================================
   THE ONLY FILE YOU EDIT TO ADD A DIVISION.

   Navigation, the homepage grid, the 3D scroll beats, /services/[division]
   routing, the inquiry form, metadata and sitemap.xml all render from this
   array. See README.md > "Adding a division".
   ========================================================================= */

export interface DivisionService {
  title: string;
  body: string;
}

export interface Division {
  /** URL segment: /services/<slug> */
  slug: string;
  /** Full name, used in headings and metadata. */
  name: string;
  /** Compact name for nav and cards. */
  shortName: string;
  /** One line, sentence case, no period. */
  tagline: string;
  /** 1-2 sentences under the H1. */
  summary: string;
  /** Body copy, one string per paragraph. */
  body: string[];
  /** Rendered as the "What we do" list. */
  services: DivisionService[];
  /** Short trust / at-a-glance points. */
  highlights: string[];
  /**
   * The division's colour, used everywhere at once: the card, the page hero,
   * the form focus ring, the active rail tick and the 3D slab's edge glow.
   * Verified for WCAG AA by `node scripts/check-contrast.mjs`.
   */
  theme: DivisionTheme;
  /**
   * The division's artwork. Generated by
   * `node scripts/generate-division-images.mjs`; swap the file at `src` for
   * real photography without touching any component. See README > Imagery.
   */
  image: { src: string; alt: string };
  /** The geometry archetype for this division's 3D scroll moment. */
  scene: {
    shape: 'slab' | 'ring' | 'prism' | 'lattice' | 'column' | 'arc' | 'stack';
  };
  /** Optional legal/regulatory notice rendered prominently on the page. */
  notice?: string;
  form: FormConfig;
  seo: { title: string; description: string };
}

const contactBlock = (extra = ''): string =>
  `Tell us what you need and we will come back with next steps.${extra ? ` ${extra}` : ''}`;

export const divisions: Division[] = [
  /* ---------------------------------------------------------------- 1 */
  {
    slug: 'automotive',
    name: 'Automotive',
    shortName: 'Automotive',
    tagline: 'Vehicles sourced, sold and serviced',
    summary:
      'Vehicle listings, help finding the right car, and support through the buying and selling process.',
    body: [
      'Our automotive division works on both sides of a vehicle transaction. If you are selling, we help you present the vehicle and reach buyers. If you are buying, we help you find a vehicle that matches your budget, use case and timeline instead of scrolling listings alone.',
      'We also coordinate the practical work around a vehicle: inspections, servicing, and the paperwork that goes with a change of ownership.',
    ],
    services: [
      {
        title: 'Vehicle listings',
        body: 'Current vehicles available through TKG Ventures, presented with clear condition and pricing details.',
      },
      {
        title: 'Vehicle sourcing',
        body: 'Tell us the make, model, budget and timeline. We search on your behalf and bring back options.',
      },
      {
        title: 'Selling assistance',
        body: 'Help preparing, pricing and listing a vehicle you want to move.',
      },
      {
        title: 'Automotive services',
        body: 'Coordination of inspection, servicing and maintenance work.',
      },
      {
        title: 'Dealership solutions',
        body: 'Streamlined vehicle sales and digital dealership solutions.',
      },
    ],
    highlights: ['Buying and selling support', 'Sourcing to your spec', 'Inspection coordination'],
    theme: {
      accent: '#BC4A17',
      accentInk: '#96380F',
      accentSoft: '#FBEBE2',
      accentContrast: '#FFFFFF',
      accentBright: '#FF9163',
      glow: '#FF8A4C',
    },
    image: {
      src: '/divisions/automotive.jpg',
      alt:
        'A line of dark vehicles parked under low showroom lighting.',
    },
    scene: { shape: 'slab' },
    form: {
      title: 'Automotive inquiry',
      intro: contactBlock('The more detail on the vehicle, the faster we can help.'),
      submitLabel: 'Send automotive inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'What do you need?',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'buying', label: 'I am looking to buy' },
            { value: 'selling', label: 'I am looking to sell' },
            { value: 'sourcing', label: 'Find a specific vehicle for me' },
            { value: 'service', label: 'Servicing or inspection' },
          ],
        },
        {
          name: 'vehicle',
          label: 'Make / model of interest',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. Toyota RAV4, 2019+',
        },
        {
          name: 'budget',
          label: 'Budget range',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 18,000 - 25,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '2-4-weeks', label: 'Within 2-4 weeks' },
            { value: '1-3-months', label: '1-3 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'Condition, mileage, trim, financing needs, or anything else that helps.',
        },
      ],
    },
    seo: {
      title: 'Automotive - vehicle sales, sourcing and services',
      description:
        'Vehicle listings, sourcing to your specification, selling assistance and automotive service coordination from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 2 */
  {
    slug: 'real-estate',
    name: 'Real Estate',
    shortName: 'Real Estate',
    tagline: 'Connected to licensed representation',
    summary: 'Properties for sale, buy and sell assistance, and introductions to licensed realtors.',
    body: [
      'Property decisions are rarely just about the property. Our real estate division helps you get oriented: what is on the market, what your place might be worth, and what the process actually looks like from here.',
      'All regulated real estate services are carried out by a licensed representative. TKG Ventures makes the connection and stays alongside you through the process.',
    ],
    services: [
      { title: 'Properties for sale', body: 'Listings available through our licensed partners.' },
      {
        title: 'Buying assistance',
        body: 'Help defining your search, understanding the area and moving through offers.',
      },
      {
        title: 'Selling assistance',
        body: 'Preparation, pricing guidance and listing through a licensed representative.',
      },
      {
        title: 'Realtor connections',
        body: 'An introduction to a licensed realtor matched to your property type and area.',
      },
    ],
    highlights: ['Licensed representation', 'Buy and sell support', 'Local market guidance'],
    theme: {
      accent: '#1F5CA8',
      accentInk: '#1B4C8A',
      accentSoft: '#E6EDF7',
      accentContrast: '#FFFFFF',
      accentBright: '#7FB6F2',
      glow: '#6FA3D8',
    },
    image: {
      src: '/divisions/real-estate.jpg',
      alt:
        'A contemporary house at dusk, warm light in its windows.',
    },
    scene: { shape: 'column' },
    notice: site.realEstate.disclaimer,
    form: {
      title: 'Real estate inquiry',
      intro: contactBlock('A licensed representative will handle any regulated services.'),
      submitLabel: 'Send real estate inquiry',
      disclaimer: site.realEstate.disclaimer,
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'intent',
          label: 'Are you buying or selling?',
          type: 'radio',
          required: true,
          options: [
            { value: 'buying', label: 'Buying' },
            { value: 'selling', label: 'Selling' },
            { value: 'both', label: 'Both' },
            { value: 'advice', label: 'Just want advice' },
          ],
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'detached', label: 'Detached house' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'land', label: 'Land' },
            { value: 'commercial', label: 'Commercial' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          name: 'area',
          label: 'Area or neighbourhood',
          type: 'text',
          required: true,
          span: 'half',
          placeholder: 'e.g. Surrey, Abbotsford',
        },
        {
          name: 'priceRange',
          label: 'Budget or expected price',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 700,000 - 900,000',
        },
        {
          name: 'timeline',
          label: 'Timeline',
          type: 'select',
          span: 'half',
          options: [
            { value: 'asap', label: 'As soon as possible' },
            { value: '1-3-months', label: '1-3 months' },
            { value: '3-6-months', label: '3-6 months' },
            { value: 'exploring', label: 'Just exploring' },
          ],
        },
        {
          name: 'details',
          label: 'Anything else we should know?',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Bedrooms, must-haves, current mortgage situation, or questions about the process.',
        },
      ],
    },
    seo: {
      title: 'Real Estate - buying, selling and licensed realtor connections',
      description:
        'Properties for sale, buying and selling assistance, and introductions to licensed realtors through TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 3 */
  {
    slug: 'security-smart-home',
    name: 'Security & Smart Home',
    shortName: 'Security',
    tagline: 'Alarms, cameras and connected homes',
    summary:
      'Alarm systems, cameras, video doorbells and smart-home equipment - supplied, installed and serviced.',
    body: [
      'A security setup only works if it is specified for the actual building and the people in it. We look at the property, recommend equipment that fits, install it properly and stay available when something needs adjusting.',
      'The same team handles smart-home equipment, so lighting, locks, thermostats and cameras end up on one coherent setup rather than five apps that do not talk to each other.',
    ],
    services: [
      {
        title: 'Smart systems',
        body: 'Protect your property with advanced automation and monitoring.',
      },
      {
        title: '24/7 monitoring',
        body: 'Reliable, real-time security for peace of mind.',
      },
      {
        title: 'Cameras & doorbells',
        body: 'Camera placement, video doorbells and recording setup for homes and businesses.',
      },
      {
        title: 'Smart-home equipment',
        body: 'Smart locks, lighting, thermostats and hubs configured to work together.',
      },
      {
        title: 'Installation',
        body: 'Professional setup for seamless, secure home integration.',
      },
    ],
    highlights: [
      'Authorized Brinks Home Security dealer',
      '24/7 monitoring',
      'Professional installation',
    ],
    theme: {
      accent: '#5A3FC0',
      accentInk: '#4A3399',
      accentSoft: '#EDE9F9',
      accentContrast: '#FFFFFF',
      accentBright: '#B39CFA',
      glow: '#9182D4',
    },
    image: {
      src: '/divisions/security-smart-home.jpg',
      alt:
        'A smart-home sensor lit in blue and magenta.',
    },
    scene: { shape: 'lattice' },
    notice:
      'TKG Ventures Ltd is an authorized dealer of Brinks Home Security, delivering professional home security and smart automation solutions across select markets.',
    form: {
      title: 'Security & smart home inquiry',
      intro: contactBlock('Tell us about the property and what you want covered.'),
      submitLabel: 'Send security inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'propertyType',
          label: 'Property type',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'house', label: 'House' },
            { value: 'townhouse', label: 'Townhouse' },
            { value: 'condo', label: 'Condo / apartment' },
            { value: 'retail', label: 'Retail unit' },
            { value: 'office', label: 'Office' },
            { value: 'warehouse', label: 'Warehouse / industrial' },
          ],
        },
        {
          name: 'systems',
          label: 'What are you interested in?',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'alarm', label: 'Alarm system' },
            { value: 'cameras', label: 'Security cameras' },
            { value: 'doorbell', label: 'Video doorbell' },
            { value: 'locks', label: 'Smart locks' },
            { value: 'lighting', label: 'Smart lighting' },
            { value: 'thermostat', label: 'Smart thermostat' },
          ],
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'new-install', label: 'New installation' },
            { value: 'upgrade', label: 'Upgrade existing system' },
            { value: 'service', label: 'Service or repair' },
            { value: 'equipment-only', label: 'Equipment purchase only' },
          ],
        },
        {
          name: 'address',
          label: 'Service address',
          type: 'text',
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Number of entry points, existing equipment, coverage areas, monitoring preference.',
        },
      ],
    },
    seo: {
      title: 'Security & Smart Home - alarms, cameras and installation',
      description:
        'Alarm systems, security cameras, video doorbells and smart-home equipment. Supply, installation and service from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 4 */
  {
    slug: 'moving-delivery',
    name: 'Moving & Delivery',
    shortName: 'Moving',
    tagline: 'Small moves, done properly',
    summary:
      'Pickup-truck moving, furniture and appliance delivery and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    body: [
      'Not every move needs a full moving company. A studio apartment, a couch, a fridge, a Marketplace pickup two cities over - those jobs sit awkwardly between "do it yourself" and "book a crew". That is exactly the gap this division fills.',
      `We operate across the ${site.serviceArea.join(' and ')}. Give us the two addresses, a date and a rough list of what is moving, and we will come back with a price.`,
    ],
    services: [
      {
        title: 'Small & residential moves',
        body: 'Studio, one-bedroom and partial moves handled with a pickup truck and care.',
      },
      {
        title: 'Furniture & appliance delivery',
        body: 'Single-item delivery from store, warehouse or private seller to your door.',
      },
      {
        title: 'Marketplace pickups',
        body: 'We collect your online marketplace purchase and bring it to you.',
      },
      { title: 'Junk & load runs', body: 'Single-load removal and transport runs.' },
    ],
    highlights: [site.serviceArea.join(' & '), 'Single items to small moves', 'Flexible scheduling'],
    theme: {
      accent: '#9A6206',
      accentInk: '#7C4E05',
      accentSoft: '#FAEFD9',
      accentContrast: '#FFFFFF',
      accentBright: '#F0AE43',
      glow: '#D2A24F',
    },
    image: {
      src: '/divisions/moving-delivery.jpg',
      alt:
        'Stacked cardboard cartons on a pallet in a warehouse.',
    },
    scene: { shape: 'stack' },
    form: {
      title: 'Moving & delivery quote',
      intro: contactBlock('Both addresses and a rough item list get you the fastest quote.'),
      submitLabel: 'Request moving quote',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'jobType',
          label: 'Type of job',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'small-move', label: 'Small / residential move' },
            { value: 'furniture-delivery', label: 'Furniture or appliance delivery' },
            { value: 'marketplace-pickup', label: 'Marketplace pickup' },
            { value: 'single-item', label: 'Single item transport' },
            { value: 'junk-run', label: 'Junk / load run' },
          ],
        },
        {
          name: 'pickupAddress',
          label: 'Pickup address',
          type: 'text',
          required: true,
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'dropoffAddress',
          label: 'Drop-off address',
          type: 'text',
          required: true,
          span: 'half',
          placeholder: 'Street, city',
        },
        { name: 'date', label: 'Preferred date', type: 'date', required: true, span: 'half' },
        {
          name: 'access',
          label: 'Access at either end',
          type: 'select',
          span: 'half',
          options: [
            { value: 'ground', label: 'Ground floor both ends' },
            { value: 'elevator', label: 'Elevator available' },
            { value: 'stairs', label: 'Stairs involved' },
            { value: 'unsure', label: 'Not sure yet' },
          ],
        },
        {
          name: 'items',
          label: 'What is being moved?',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder: 'e.g. 3-seat sofa, queen bed frame + mattress, 8 boxes, fridge.',
        },
      ],
    },
    seo: {
      title: 'Moving & Delivery - small moves and furniture delivery',
      description:
        'Pickup-truck moving, furniture and appliance delivery, and Marketplace pickups across the Lower Mainland and Fraser Valley.',
    },
  },

  /* ---------------------------------------------------------------- 5 */
  {
    slug: 'cleaning-staffing',
    name: 'Cleaning & Staffing',
    shortName: 'Cleaning',
    tagline: 'Clean spaces and the people to keep them that way',
    summary:
      'Residential and commercial cleaning, plus cleaning staff supplied to businesses that need their own team.',
    body: [
      'Two related things happen in this division. We clean - homes, offices, units between tenants, sites after a job. And we supply cleaning staff to businesses that would rather have their own consistent team on site.',
      'Whichever you need, the starting point is the same: the size of the space, how often it needs doing, and any specific requirements.',
    ],
    services: [
      {
        title: 'Residential cleaning',
        body: 'Regular, one-off, move-in and move-out cleans for homes and rentals.',
      },
      {
        title: 'Commercial cleaning',
        body: 'Offices, retail units and shared spaces on a schedule that suits the business.',
      },
      {
        title: 'Staff supply',
        body: 'Cleaning staff and manpower supplied to businesses that manage their own operation.',
      },
      {
        title: 'Post-construction & turnover',
        body: 'Detailed cleans after building work or between tenancies.',
      },
    ],
    highlights: ['Residential & commercial', 'One-off or recurring', 'Staff supply available'],
    theme: {
      accent: '#07786A',
      accentInk: '#065E53',
      accentSoft: '#DFF2EF',
      accentContrast: '#FFFFFF',
      accentBright: '#3FD9C0',
      glow: '#4FB3A3',
    },
    image: {
      src: '/divisions/cleaning-staffing.jpg',
      alt:
        'A bright, spotless living room with white furnishings.',
    },
    scene: { shape: 'ring' },
    form: {
      title: 'Cleaning & staffing inquiry',
      intro: contactBlock('Space size and frequency are the two things we need most.'),
      submitLabel: 'Send cleaning inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'serviceType',
          label: 'What do you need?',
          type: 'radio',
          required: true,
          options: [
            { value: 'residential', label: 'Residential cleaning' },
            { value: 'commercial', label: 'Commercial cleaning' },
            { value: 'staffing', label: 'Cleaning staff supply' },
            { value: 'post-construction', label: 'Post-construction / turnover' },
          ],
        },
        {
          name: 'frequency',
          label: 'Frequency',
          type: 'select',
          required: true,
          span: 'half',
          options: [
            { value: 'one-off', label: 'One-off' },
            { value: 'weekly', label: 'Weekly' },
            { value: 'biweekly', label: 'Every two weeks' },
            { value: 'monthly', label: 'Monthly' },
            { value: 'ongoing-staff', label: 'Ongoing staff placement' },
          ],
        },
        {
          name: 'size',
          label: 'Size of space',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. 3 bed / 2 bath, or 2,500 sq ft office',
        },
        {
          name: 'address',
          label: 'Location',
          type: 'text',
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'City or full address',
        },
        { name: 'startDate', label: 'Preferred start date', type: 'date', span: 'half' },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          rows: 5,
          placeholder:
            'Access, supplies, hours of day, number of staff needed, special requirements.',
        },
      ],
    },
    seo: {
      title: 'Cleaning & Staffing - residential, commercial and staff supply',
      description:
        'Residential and commercial cleaning plus supplied cleaning staff and manpower from TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 6 */
  {
    slug: 'telecommunications',
    name: 'Telecommunications',
    shortName: 'Telecom',
    tagline: 'Internet, TV and phone, without the runaround',
    summary: 'Internet, television and phone plans - compared, explained and set up.',
    body: [
      'Telecom pricing is deliberately hard to compare. This division does the comparing for you: what is actually available at your address, what the real monthly cost looks like after promotional periods, and whether switching is worth the effort.',
      'We handle home and business connections, new installs and switches from an existing provider.',
    ],
    services: [
      {
        title: 'Internet',
        body: 'Home and business internet plans matched to how you actually use the connection.',
      },
      { title: 'Television', body: 'TV packages and streaming alternatives, compared honestly.' },
      { title: 'Phone', body: 'Home phone and mobile plans, including business lines.' },
      {
        title: 'Offers & switching',
        body: 'Current promotions and help moving from your existing provider.',
      },
    ],
    highlights: ['Home & business', 'Plan comparison', 'Switching support'],
    theme: {
      accent: '#08718F',
      accentInk: '#065A72',
      accentSoft: '#DEF0F6',
      accentContrast: '#FFFFFF',
      accentBright: '#4FCBEB',
      glow: '#46A9C6',
    },
    image: {
      src: '/divisions/telecommunications.jpg',
      alt:
        'Illuminated fibre-optic strands against a black background.',
    },
    scene: { shape: 'arc' },
    form: {
      title: 'Telecommunications inquiry',
      intro: contactBlock('Your address determines what is actually available.'),
      submitLabel: 'Send telecom inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'accountType',
          label: 'Home or business?',
          type: 'radio',
          required: true,
          options: [
            { value: 'home', label: 'Home' },
            { value: 'business', label: 'Business' },
          ],
        },
        {
          name: 'services',
          label: 'Services you want',
          type: 'checkbox-group',
          required: true,
          options: [
            { value: 'internet', label: 'Internet' },
            { value: 'tv', label: 'TV' },
            { value: 'home-phone', label: 'Home phone' },
            { value: 'mobile', label: 'Mobile' },
          ],
        },
        {
          name: 'address',
          label: 'Service address',
          type: 'text',
          required: true,
          span: 'half',
          autoComplete: 'street-address',
          placeholder: 'Street, city',
        },
        {
          name: 'currentProvider',
          label: 'Current provider (if any)',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. none',
        },
        {
          name: 'details',
          label: 'What matters most?',
          type: 'textarea',
          rows: 4,
          placeholder:
            'Speed, price, contract length, number of users, channels you actually watch.',
        },
      ],
    },
    seo: {
      title: 'Telecommunications - internet, TV and phone plans',
      description:
        'Internet, television and phone plans for home and business, compared and set up by TKG Ventures.',
    },
  },

  /* ---------------------------------------------------------------- 7 */
  {
    slug: 'business-services',
    name: 'Business Services',
    shortName: 'Business',
    tagline: 'Opportunities, referrals and growth support',
    summary:
      'Business opportunities, businesses for sale, referrals, and marketing and lead generation support.',
    body: [
      'This division is deliberately broad. It covers the work that does not fit neatly into the other six: businesses changing hands, opportunities worth looking at, introductions between people who should be talking, and help finding customers.',
      'If you are not sure which division your question belongs to, start here.',
    ],
    services: [
      { title: 'Businesses for sale', body: 'Operating businesses available through our network.' },
      { title: 'Business opportunities', body: 'Ventures and partnerships worth a conversation.' },
      {
        title: 'Referrals',
        body: 'Introductions to vetted providers inside and outside our divisions.',
      },
      {
        title: 'Lead generation',
        body: 'Drive growth with targeted outreach and expert sales strategies.',
      },
      {
        title: 'Brand strategy',
        body: 'Position your business for success with proven marketing solutions.',
      },
      {
        title: 'Market insights',
        body: 'Unlock actionable data to inform smarter business decisions.',
      },
      {
        title: 'Digital solutions',
        body: 'Custom software, SaaS and modern, responsive web design.',
      },
    ],
    highlights: ['Lead generation and brand strategy', 'Software and web design', 'Referral network'],
    theme: {
      accent: '#4A7A1C',
      accentInk: '#3B6116',
      accentSoft: '#EEF4E2',
      accentContrast: '#FFFFFF',
      accentBright: '#A2DD5F',
      glow: '#86AC5C',
    },
    image: {
      src: '/divisions/business-services.jpg',
      alt:
        'An overhead view of a tidy desk with a laptop and notebook.',
    },
    scene: { shape: 'prism' },
    form: {
      title: 'Business services inquiry',
      intro: contactBlock('Tell us what you are working on and we will point you the right way.'),
      submitLabel: 'Send business inquiry',
      fields: [
        {
          name: 'phone',
          label: 'Phone',
          type: 'tel',
          required: true,
          span: 'half',
          autoComplete: 'tel',
          placeholder: '(000) 000-0000',
        },
        {
          name: 'company',
          label: 'Company (optional)',
          type: 'text',
          span: 'half',
          autoComplete: 'organization',
        },
        {
          name: 'interest',
          label: 'What brings you here?',
          type: 'select',
          required: true,
          options: [
            { value: 'buy-business', label: 'Looking to buy a business' },
            { value: 'sell-business', label: 'Looking to sell a business' },
            { value: 'opportunity', label: 'Exploring an opportunity or partnership' },
            { value: 'referral', label: 'Looking for a referral' },
            { value: 'marketing', label: 'Marketing / lead generation' },
            { value: 'other', label: 'Something else' },
          ],
        },
        {
          name: 'industry',
          label: 'Industry or sector',
          type: 'text',
          span: 'half',
          placeholder: 'e.g. food service, logistics',
        },
        {
          name: 'budget',
          label: 'Budget or investment range',
          type: 'text',
          span: 'half',
          placeholder: 'Optional',
        },
        {
          name: 'details',
          label: 'Details',
          type: 'textarea',
          required: true,
          rows: 5,
          placeholder:
            'What you are trying to do, where you are in the process, and how we can help.',
        },
      ],
    },
    seo: {
      title: 'Business Services - opportunities, referrals and lead generation',
      description:
        'Business opportunities, businesses for sale, referrals and marketing support from TKG Ventures.',
    },
  },
];

/* ---------------------------------- helpers ---------------------------------- */

export const divisionSlugs: string[] = divisions.map((d) => d.slug);

export function getDivision(slug: string): Division | undefined {
  return divisions.find((d) => d.slug === slug);
}

export function divisionPath(slug: string): string {
  return `/services/${slug}`;
}
